//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgIdentityService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgIdentityService.IdentityInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgIdentityService.PersonInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgIdentityService.OrganizationInfo))]
    public partial class BaseCrmObjectInfo : object
    {
        
        private System.DateTime CreatDateField;
        
        private System.Nullable<System.Guid> CrmIdField;
        
        private string CrmObjectTypeCodeField;
        
        private System.Guid CrmObjectTypeIdField;
        
        private int CrmObjectTypeIndexField;
        
        private string CrmObjectTypeNameField;
        
        private PgIdentityService.BaseCrmObjectExtendedPropertyInfo[] ExtendedPropertiesField;
        
        private System.DateTime ModifyDateField;
        
        private System.Nullable<System.Guid> ParentCrmObjectIdField;
        
        private System.Nullable<int> ProcessStateIndexField;
        
        private string RefIdField;
        
        private string StageField;
        
        private System.Nullable<System.Guid> StageIdField;
        
        private string[] TagsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatDate
        {
            get
            {
                return this.CreatDateField;
            }
            set
            {
                this.CreatDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CrmId
        {
            get
            {
                return this.CrmIdField;
            }
            set
            {
                this.CrmIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeCode
        {
            get
            {
                return this.CrmObjectTypeCodeField;
            }
            set
            {
                this.CrmObjectTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CrmObjectTypeId
        {
            get
            {
                return this.CrmObjectTypeIdField;
            }
            set
            {
                this.CrmObjectTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrmObjectTypeIndex
        {
            get
            {
                return this.CrmObjectTypeIndexField;
            }
            set
            {
                this.CrmObjectTypeIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeName
        {
            get
            {
                return this.CrmObjectTypeNameField;
            }
            set
            {
                this.CrmObjectTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgIdentityService.BaseCrmObjectExtendedPropertyInfo[] ExtendedProperties
        {
            get
            {
                return this.ExtendedPropertiesField;
            }
            set
            {
                this.ExtendedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyDate
        {
            get
            {
                return this.ModifyDateField;
            }
            set
            {
                this.ModifyDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentCrmObjectId
        {
            get
            {
                return this.ParentCrmObjectIdField;
            }
            set
            {
                this.ParentCrmObjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProcessStateIndex
        {
            get
            {
                return this.ProcessStateIndexField;
            }
            set
            {
                this.ProcessStateIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId
        {
            get
            {
                return this.RefIdField;
            }
            set
            {
                this.RefIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stage
        {
            get
            {
                return this.StageField;
            }
            set
            {
                this.StageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> StageId
        {
            get
            {
                return this.StageIdField;
            }
            set
            {
                this.StageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgIdentityService.PersonInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgIdentityService.OrganizationInfo))]
    public partial class IdentityInfo : PgIdentityService.BaseCrmObjectInfo
    {
        
        private PgIdentityService.IdentityContactAddress[] AddressContactsField;
        
        private System.Nullable<decimal> BalanceField;
        
        private PgIdentityService.CategoryInfo[] CategoriesField;
        
        private string ClassificationField;
        
        private string ColorNameField;
        
        private System.Nullable<System.DateTime> CustomerDateField;
        
        private string CustomerNumberField;
        
        private System.Nullable<bool> DontEmailField;
        
        private System.Nullable<bool> DontFaxField;
        
        private System.Nullable<bool> DontPhoneCallField;
        
        private System.Nullable<bool> DontSmsField;
        
        private System.Nullable<bool> DontSocialSmsField;
        
        private string[] EmailsField;
        
        private string IdentityTypeField;
        
        private string NickNameField;
        
        private string OtherUsernameField;
        
        private PgIdentityService.IdentityContactPhone[] PhoneContactsField;
        
        private string SaleUsernameField;
        
        private string SourceTypeField;
        
        private string SupportUsernameField;
        
        private string WebsiteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgIdentityService.IdentityContactAddress[] AddressContacts
        {
            get
            {
                return this.AddressContactsField;
            }
            set
            {
                this.AddressContactsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgIdentityService.CategoryInfo[] Categories
        {
            get
            {
                return this.CategoriesField;
            }
            set
            {
                this.CategoriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification
        {
            get
            {
                return this.ClassificationField;
            }
            set
            {
                this.ClassificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorName
        {
            get
            {
                return this.ColorNameField;
            }
            set
            {
                this.ColorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CustomerDate
        {
            get
            {
                return this.CustomerDateField;
            }
            set
            {
                this.CustomerDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNumber
        {
            get
            {
                return this.CustomerNumberField;
            }
            set
            {
                this.CustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DontEmail
        {
            get
            {
                return this.DontEmailField;
            }
            set
            {
                this.DontEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DontFax
        {
            get
            {
                return this.DontFaxField;
            }
            set
            {
                this.DontFaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DontPhoneCall
        {
            get
            {
                return this.DontPhoneCallField;
            }
            set
            {
                this.DontPhoneCallField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DontSms
        {
            get
            {
                return this.DontSmsField;
            }
            set
            {
                this.DontSmsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DontSocialSms
        {
            get
            {
                return this.DontSocialSmsField;
            }
            set
            {
                this.DontSocialSmsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Emails
        {
            get
            {
                return this.EmailsField;
            }
            set
            {
                this.EmailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityType
        {
            get
            {
                return this.IdentityTypeField;
            }
            set
            {
                this.IdentityTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName
        {
            get
            {
                return this.NickNameField;
            }
            set
            {
                this.NickNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherUsername
        {
            get
            {
                return this.OtherUsernameField;
            }
            set
            {
                this.OtherUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgIdentityService.IdentityContactPhone[] PhoneContacts
        {
            get
            {
                return this.PhoneContactsField;
            }
            set
            {
                this.PhoneContactsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaleUsername
        {
            get
            {
                return this.SaleUsernameField;
            }
            set
            {
                this.SaleUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceType
        {
            get
            {
                return this.SourceTypeField;
            }
            set
            {
                this.SourceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupportUsername
        {
            get
            {
                return this.SupportUsernameField;
            }
            set
            {
                this.SupportUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website
        {
            get
            {
                return this.WebsiteField;
            }
            set
            {
                this.WebsiteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class PersonInfo : PgIdentityService.IdentityInfo
    {
        
        private string AreasOfInterestField;
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        private string ChildrenField;
        
        private string CreditTypeField;
        
        private string DegreeField;
        
        private PgIdentityService.EmployeeInfo[] EmployeesField;
        
        private string FacebookUsernameField;
        
        private string FirstNameField;
        
        private string GenderField;
        
        private string HobbiesField;
        
        private string LastNameField;
        
        private string MannerTypeField;
        
        private string NationalCodeField;
        
        private string PaymentStatusTypeField;
        
        private string PersonPrefixField;
        
        private string PrefferedContactTypeField;
        
        private string SpouseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreasOfInterest
        {
            get
            {
                return this.AreasOfInterestField;
            }
            set
            {
                this.AreasOfInterestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Children
        {
            get
            {
                return this.ChildrenField;
            }
            set
            {
                this.ChildrenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditType
        {
            get
            {
                return this.CreditTypeField;
            }
            set
            {
                this.CreditTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Degree
        {
            get
            {
                return this.DegreeField;
            }
            set
            {
                this.DegreeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgIdentityService.EmployeeInfo[] Employees
        {
            get
            {
                return this.EmployeesField;
            }
            set
            {
                this.EmployeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookUsername
        {
            get
            {
                return this.FacebookUsernameField;
            }
            set
            {
                this.FacebookUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hobbies
        {
            get
            {
                return this.HobbiesField;
            }
            set
            {
                this.HobbiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MannerType
        {
            get
            {
                return this.MannerTypeField;
            }
            set
            {
                this.MannerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalCode
        {
            get
            {
                return this.NationalCodeField;
            }
            set
            {
                this.NationalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentStatusType
        {
            get
            {
                return this.PaymentStatusTypeField;
            }
            set
            {
                this.PaymentStatusTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonPrefix
        {
            get
            {
                return this.PersonPrefixField;
            }
            set
            {
                this.PersonPrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrefferedContactType
        {
            get
            {
                return this.PrefferedContactTypeField;
            }
            set
            {
                this.PrefferedContactTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Spouse
        {
            get
            {
                return this.SpouseField;
            }
            set
            {
                this.SpouseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class OrganizationInfo : PgIdentityService.IdentityInfo
    {
        
        private string BusinessTypeField;
        
        private string EconomicCodeField;
        
        private System.Nullable<System.Guid> ManagerIdField;
        
        private string OwnershipTypeField;
        
        private PgIdentityService.EmployeeInfo[] PersonnelField;
        
        private System.Nullable<System.DateTime> RegisterDateField;
        
        private string RegisterNumberField;
        
        private string ShareTypeField;
        
        private string TradeTypeField;
        
        private string TrademarkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessType
        {
            get
            {
                return this.BusinessTypeField;
            }
            set
            {
                this.BusinessTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EconomicCode
        {
            get
            {
                return this.EconomicCodeField;
            }
            set
            {
                this.EconomicCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ManagerId
        {
            get
            {
                return this.ManagerIdField;
            }
            set
            {
                this.ManagerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnershipType
        {
            get
            {
                return this.OwnershipTypeField;
            }
            set
            {
                this.OwnershipTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgIdentityService.EmployeeInfo[] Personnel
        {
            get
            {
                return this.PersonnelField;
            }
            set
            {
                this.PersonnelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegisterDate
        {
            get
            {
                return this.RegisterDateField;
            }
            set
            {
                this.RegisterDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisterNumber
        {
            get
            {
                return this.RegisterNumberField;
            }
            set
            {
                this.RegisterNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareType
        {
            get
            {
                return this.ShareTypeField;
            }
            set
            {
                this.ShareTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeType
        {
            get
            {
                return this.TradeTypeField;
            }
            set
            {
                this.TradeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trademark
        {
            get
            {
                return this.TrademarkField;
            }
            set
            {
                this.TrademarkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectExtendedPropertyInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class BaseCrmObjectExtendedPropertyInfo : object
    {
        
        private string NameField;
        
        private string UserKeyField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityContactAddress", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class IdentityContactAddress : PgIdentityService.IdentityContact
    {
        
        private string AddressField;
        
        private string AddressTypeField;
        
        private string AreaCodeField;
        
        private string CityField;
        
        private string CountryField;
        
        private string StateField;
        
        private string ZipBoxField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressType
        {
            get
            {
                return this.AddressTypeField;
            }
            set
            {
                this.AddressTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaCode
        {
            get
            {
                return this.AreaCodeField;
            }
            set
            {
                this.AreaCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipBox
        {
            get
            {
                return this.ZipBoxField;
            }
            set
            {
                this.ZipBoxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class CategoryInfo : object
    {
        
        private System.Guid IdField;
        
        private System.Guid IdentityIdField;
        
        private bool IsDeletedField;
        
        private string KeyField;
        
        private string NameField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdentityId
        {
            get
            {
                return this.IdentityIdField;
            }
            set
            {
                this.IdentityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityContactPhone", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class IdentityContactPhone : PgIdentityService.IdentityContact
    {
        
        private string ContinuedNumberField;
        
        private string ExtensionField;
        
        private string PhoneNumberField;
        
        private string PhoneTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContinuedNumber
        {
            get
            {
                return this.ContinuedNumberField;
            }
            set
            {
                this.ContinuedNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneType
        {
            get
            {
                return this.PhoneTypeField;
            }
            set
            {
                this.PhoneTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityContact", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgIdentityService.IdentityContactPhone))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgIdentityService.IdentityContactAddress))]
    public partial class IdentityContact : object
    {
        
        private System.Guid IdField;
        
        private bool IsDefaultField;
        
        private bool IsDeletedField;
        
        private string RefIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefault
        {
            get
            {
                return this.IsDefaultField;
            }
            set
            {
                this.IsDefaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId
        {
            get
            {
                return this.RefIdField;
            }
            set
            {
                this.RefIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class EmployeeInfo : object
    {
        
        private string DepartmentField;
        
        private System.Guid IdField;
        
        private bool IsDeletedField;
        
        private string JobTypeField;
        
        private string OfficeField;
        
        private System.Guid OrganizationIdField;
        
        private System.Guid PersonIdField;
        
        private string ProfessionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobType
        {
            get
            {
                return this.JobTypeField;
            }
            set
            {
                this.JobTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Office
        {
            get
            {
                return this.OfficeField;
            }
            set
            {
                this.OfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrganizationId
        {
            get
            {
                return this.OrganizationIdField;
            }
            set
            {
                this.OrganizationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PersonId
        {
            get
            {
                return this.PersonIdField;
            }
            set
            {
                this.PersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Profession
        {
            get
            {
                return this.ProfessionField;
            }
            set
            {
                this.ProfessionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgIdentityService.IdentityInfoResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgIdentityService.SaveCrmObjectResult))]
    public partial class OperationResult : object
    {
        
        private string MessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityInfoResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class IdentityInfoResult : PgIdentityService.OperationResult
    {
        
        private PgIdentityService.IdentityInfo IdentityInfoField;
        
        private PgIdentityService.IdentityInfo[] IdentityInfoListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgIdentityService.IdentityInfo IdentityInfo
        {
            get
            {
                return this.IdentityInfoField;
            }
            set
            {
                this.IdentityInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgIdentityService.IdentityInfo[] IdentityInfoList
        {
            get
            {
                return this.IdentityInfoListField;
            }
            set
            {
                this.IdentityInfoListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveCrmObjectResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class SaveCrmObjectResult : PgIdentityService.OperationResult
    {
        
        private System.Guid CrmIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CrmId
        {
            get
            {
                return this.CrmIdField;
            }
            set
            {
                this.CrmIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectDeleteOption", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.Domain.Model")]
    public enum CrmObjectDeleteOption : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssignChildrenToParent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteChildren = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nothing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeletePersons = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteWithHistory = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PgIdentityService.IIdentity")]
    public interface IIdentity
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentity/SaveIdentity", ReplyAction="http://tempuri.org/IIdentity/SaveIdentityResponse")]
        PgIdentityService.SaveCrmObjectResult SaveIdentity(string username, string password, PgIdentityService.IdentityInfo identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentity/SaveIdentity", ReplyAction="http://tempuri.org/IIdentity/SaveIdentityResponse")]
        System.Threading.Tasks.Task<PgIdentityService.SaveCrmObjectResult> SaveIdentityAsync(string username, string password, PgIdentityService.IdentityInfo identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentity/SearchIdentity", ReplyAction="http://tempuri.org/IIdentity/SearchIdentityResponse")]
        PgIdentityService.IdentityInfoResult SearchIdentity(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentity/SearchIdentity", ReplyAction="http://tempuri.org/IIdentity/SearchIdentityResponse")]
        System.Threading.Tasks.Task<PgIdentityService.IdentityInfoResult> SearchIdentityAsync(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentity/FindIdentityById", ReplyAction="http://tempuri.org/IIdentity/FindIdentityByIdResponse")]
        PgIdentityService.IdentityInfoResult FindIdentityById(string username, string password, System.Guid identityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentity/FindIdentityById", ReplyAction="http://tempuri.org/IIdentity/FindIdentityByIdResponse")]
        System.Threading.Tasks.Task<PgIdentityService.IdentityInfoResult> FindIdentityByIdAsync(string username, string password, System.Guid identityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentity/DeleteIdentityById", ReplyAction="http://tempuri.org/IIdentity/DeleteIdentityByIdResponse")]
        PgIdentityService.SaveCrmObjectResult DeleteIdentityById(string userName, string password, System.Guid identityId, PgIdentityService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentity/DeleteIdentityById", ReplyAction="http://tempuri.org/IIdentity/DeleteIdentityByIdResponse")]
        System.Threading.Tasks.Task<PgIdentityService.SaveCrmObjectResult> DeleteIdentityByIdAsync(string userName, string password, System.Guid identityId, PgIdentityService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentity/FindIdentityByPhoneNumber", ReplyAction="http://tempuri.org/IIdentity/FindIdentityByPhoneNumberResponse")]
        PgIdentityService.IdentityInfoResult FindIdentityByPhoneNumber(string username, string password, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentity/FindIdentityByPhoneNumber", ReplyAction="http://tempuri.org/IIdentity/FindIdentityByPhoneNumberResponse")]
        System.Threading.Tasks.Task<PgIdentityService.IdentityInfoResult> FindIdentityByPhoneNumberAsync(string username, string password, string phoneNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IIdentityChannel : PgIdentityService.IIdentity, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class IdentityClient : System.ServiceModel.ClientBase<PgIdentityService.IIdentity>, PgIdentityService.IIdentity
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IdentityClient() : 
                base(IdentityClient.GetDefaultBinding(), IdentityClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IIdentity.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IdentityClient(EndpointConfiguration endpointConfiguration) : 
                base(IdentityClient.GetBindingForEndpoint(endpointConfiguration), IdentityClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IdentityClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IdentityClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IdentityClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IdentityClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IdentityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PgIdentityService.SaveCrmObjectResult SaveIdentity(string username, string password, PgIdentityService.IdentityInfo identity)
        {
            return base.Channel.SaveIdentity(username, password, identity);
        }
        
        public System.Threading.Tasks.Task<PgIdentityService.SaveCrmObjectResult> SaveIdentityAsync(string username, string password, PgIdentityService.IdentityInfo identity)
        {
            return base.Channel.SaveIdentityAsync(username, password, identity);
        }
        
        public PgIdentityService.IdentityInfoResult SearchIdentity(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchIdentity(userName, password, typeKey, query);
        }
        
        public System.Threading.Tasks.Task<PgIdentityService.IdentityInfoResult> SearchIdentityAsync(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchIdentityAsync(userName, password, typeKey, query);
        }
        
        public PgIdentityService.IdentityInfoResult FindIdentityById(string username, string password, System.Guid identityId)
        {
            return base.Channel.FindIdentityById(username, password, identityId);
        }
        
        public System.Threading.Tasks.Task<PgIdentityService.IdentityInfoResult> FindIdentityByIdAsync(string username, string password, System.Guid identityId)
        {
            return base.Channel.FindIdentityByIdAsync(username, password, identityId);
        }
        
        public PgIdentityService.SaveCrmObjectResult DeleteIdentityById(string userName, string password, System.Guid identityId, PgIdentityService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteIdentityById(userName, password, identityId, deleteOption);
        }
        
        public System.Threading.Tasks.Task<PgIdentityService.SaveCrmObjectResult> DeleteIdentityByIdAsync(string userName, string password, System.Guid identityId, PgIdentityService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteIdentityByIdAsync(userName, password, identityId, deleteOption);
        }
        
        public PgIdentityService.IdentityInfoResult FindIdentityByPhoneNumber(string username, string password, string phoneNumber)
        {
            return base.Channel.FindIdentityByPhoneNumber(username, password, phoneNumber);
        }
        
        public System.Threading.Tasks.Task<PgIdentityService.IdentityInfoResult> FindIdentityByPhoneNumberAsync(string username, string password, string phoneNumber)
        {
            return base.Channel.FindIdentityByPhoneNumberAsync(username, password, phoneNumber);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIdentity))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIdentity))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.11.9/Services/API/IIdentity.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IdentityClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IIdentity);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IdentityClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IIdentity);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IIdentity,
        }
    }
}
