//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgInvoiceService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgInvoiceService.GeneralCrmObjectInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgInvoiceService.BaseBillableObjectInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgInvoiceService.ReturnInvoiceInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgInvoiceService.InvoiceInfo))]
    public partial class BaseCrmObjectInfo : object
    {
        
        private System.DateTime CreatDateField;
        
        private System.Nullable<System.Guid> CrmIdField;
        
        private string CrmObjectTypeCodeField;
        
        private System.Guid CrmObjectTypeIdField;
        
        private int CrmObjectTypeIndexField;
        
        private string CrmObjectTypeNameField;
        
        private PgInvoiceService.BaseCrmObjectExtendedPropertyInfo[] ExtendedPropertiesField;
        
        private System.DateTime ModifyDateField;
        
        private System.Nullable<System.Guid> ParentCrmObjectIdField;
        
        private System.Nullable<int> ProcessStateIndexField;
        
        private string RefIdField;
        
        private string StageField;
        
        private System.Nullable<System.Guid> StageIdField;
        
        private string[] TagsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatDate
        {
            get
            {
                return this.CreatDateField;
            }
            set
            {
                this.CreatDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CrmId
        {
            get
            {
                return this.CrmIdField;
            }
            set
            {
                this.CrmIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeCode
        {
            get
            {
                return this.CrmObjectTypeCodeField;
            }
            set
            {
                this.CrmObjectTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CrmObjectTypeId
        {
            get
            {
                return this.CrmObjectTypeIdField;
            }
            set
            {
                this.CrmObjectTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrmObjectTypeIndex
        {
            get
            {
                return this.CrmObjectTypeIndexField;
            }
            set
            {
                this.CrmObjectTypeIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeName
        {
            get
            {
                return this.CrmObjectTypeNameField;
            }
            set
            {
                this.CrmObjectTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgInvoiceService.BaseCrmObjectExtendedPropertyInfo[] ExtendedProperties
        {
            get
            {
                return this.ExtendedPropertiesField;
            }
            set
            {
                this.ExtendedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyDate
        {
            get
            {
                return this.ModifyDateField;
            }
            set
            {
                this.ModifyDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentCrmObjectId
        {
            get
            {
                return this.ParentCrmObjectIdField;
            }
            set
            {
                this.ParentCrmObjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProcessStateIndex
        {
            get
            {
                return this.ProcessStateIndexField;
            }
            set
            {
                this.ProcessStateIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId
        {
            get
            {
                return this.RefIdField;
            }
            set
            {
                this.RefIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stage
        {
            get
            {
                return this.StageField;
            }
            set
            {
                this.StageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> StageId
        {
            get
            {
                return this.StageIdField;
            }
            set
            {
                this.StageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralCrmObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgInvoiceService.BaseBillableObjectInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgInvoiceService.ReturnInvoiceInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgInvoiceService.InvoiceInfo))]
    public partial class GeneralCrmObjectInfo : PgInvoiceService.BaseCrmObjectInfo
    {
        
        private string DescriptionField;
        
        private System.Nullable<System.Guid> IdentityIdField;
        
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> IdentityId
        {
            get
            {
                return this.IdentityIdField;
            }
            set
            {
                this.IdentityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseBillableObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgInvoiceService.ReturnInvoiceInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgInvoiceService.InvoiceInfo))]
    public partial class BaseBillableObjectInfo : PgInvoiceService.GeneralCrmObjectInfo
    {
        
        private string BillableObjectStateField;
        
        private decimal FinalValueField;
        
        private string NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillableObjectState
        {
            get
            {
                return this.BillableObjectStateField;
            }
            set
            {
                this.BillableObjectStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FinalValue
        {
            get
            {
                return this.FinalValueField;
            }
            set
            {
                this.FinalValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnInvoiceInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class ReturnInvoiceInfo : PgInvoiceService.BaseBillableObjectInfo
    {
        
        private decimal AdditionalCostsField;
        
        private PgInvoiceService.ReturnInvoiceDetailInfo[] DetailsField;
        
        private decimal DiscountField;
        
        private System.Nullable<decimal> DiscountPercentField;
        
        private System.Nullable<System.DateTime> InvoiceDateField;
        
        private string InvoiceTypeField;
        
        private decimal TollField;
        
        private int TollPercentField;
        
        private decimal TotalValueField;
        
        private decimal VatField;
        
        private int VatPercentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AdditionalCosts
        {
            get
            {
                return this.AdditionalCostsField;
            }
            set
            {
                this.AdditionalCostsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgInvoiceService.ReturnInvoiceDetailInfo[] Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DiscountPercent
        {
            get
            {
                return this.DiscountPercentField;
            }
            set
            {
                this.DiscountPercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InvoiceDate
        {
            get
            {
                return this.InvoiceDateField;
            }
            set
            {
                this.InvoiceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceType
        {
            get
            {
                return this.InvoiceTypeField;
            }
            set
            {
                this.InvoiceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Toll
        {
            get
            {
                return this.TollField;
            }
            set
            {
                this.TollField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TollPercent
        {
            get
            {
                return this.TollPercentField;
            }
            set
            {
                this.TollPercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalValue
        {
            get
            {
                return this.TotalValueField;
            }
            set
            {
                this.TotalValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Vat
        {
            get
            {
                return this.VatField;
            }
            set
            {
                this.VatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VatPercent
        {
            get
            {
                return this.VatPercentField;
            }
            set
            {
                this.VatPercentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class InvoiceInfo : PgInvoiceService.BaseBillableObjectInfo
    {
        
        private System.Nullable<decimal> AdditionalCostsField;
        
        private string AssignedToField;
        
        private System.Nullable<System.Guid> AssignedToIdField;
        
        private PgInvoiceService.InvoiceDetailInfo[] DetailsField;
        
        private decimal DiscountField;
        
        private System.Nullable<decimal> DiscountPercentField;
        
        private System.Nullable<System.DateTime> ExpireDateField;
        
        private System.Nullable<System.DateTime> InvoiceDateField;
        
        private string InvoiceTypeField;
        
        private string PriceListNameField;
        
        private System.Nullable<System.Guid> QuoteIdField;
        
        private decimal TollField;
        
        private int TollPercentField;
        
        private decimal TotalDiscountPercentField;
        
        private decimal TotalValueField;
        
        private decimal VatField;
        
        private int VatPercentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AdditionalCosts
        {
            get
            {
                return this.AdditionalCostsField;
            }
            set
            {
                this.AdditionalCostsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedTo
        {
            get
            {
                return this.AssignedToField;
            }
            set
            {
                this.AssignedToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> AssignedToId
        {
            get
            {
                return this.AssignedToIdField;
            }
            set
            {
                this.AssignedToIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgInvoiceService.InvoiceDetailInfo[] Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DiscountPercent
        {
            get
            {
                return this.DiscountPercentField;
            }
            set
            {
                this.DiscountPercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpireDate
        {
            get
            {
                return this.ExpireDateField;
            }
            set
            {
                this.ExpireDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InvoiceDate
        {
            get
            {
                return this.InvoiceDateField;
            }
            set
            {
                this.InvoiceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceType
        {
            get
            {
                return this.InvoiceTypeField;
            }
            set
            {
                this.InvoiceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceListName
        {
            get
            {
                return this.PriceListNameField;
            }
            set
            {
                this.PriceListNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> QuoteId
        {
            get
            {
                return this.QuoteIdField;
            }
            set
            {
                this.QuoteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Toll
        {
            get
            {
                return this.TollField;
            }
            set
            {
                this.TollField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TollPercent
        {
            get
            {
                return this.TollPercentField;
            }
            set
            {
                this.TollPercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDiscountPercent
        {
            get
            {
                return this.TotalDiscountPercentField;
            }
            set
            {
                this.TotalDiscountPercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalValue
        {
            get
            {
                return this.TotalValueField;
            }
            set
            {
                this.TotalValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Vat
        {
            get
            {
                return this.VatField;
            }
            set
            {
                this.VatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VatPercent
        {
            get
            {
                return this.VatPercentField;
            }
            set
            {
                this.VatPercentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectExtendedPropertyInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class BaseCrmObjectExtendedPropertyInfo : object
    {
        
        private string NameField;
        
        private string UserKeyField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceDetailInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class InvoiceDetailInfo : object
    {
        
        private decimal BaseUnitPriceField;
        
        private decimal CountField;
        
        private string DetailDescriptionField;
        
        private System.Nullable<decimal> DiscountPercentField;
        
        private decimal FinalUnitPriceField;
        
        private int IdField;
        
        private string InventoryCodeField;
        
        private string InventoryNameField;
        
        private string InvoiceProperty0Field;
        
        private string InvoiceProperty1Field;
        
        private string InvoiceProperty10Field;
        
        private string InvoiceProperty2Field;
        
        private string InvoiceProperty3Field;
        
        private string InvoiceProperty4Field;
        
        private string InvoiceProperty5Field;
        
        private string InvoiceProperty6Field;
        
        private string InvoiceProperty7Field;
        
        private string InvoiceProperty8Field;
        
        private string InvoiceProperty9Field;
        
        private bool IsServiceField;
        
        private string ProductCodeField;
        
        private System.Nullable<System.Guid> ProductIdField;
        
        private string ProductNameField;
        
        private string ProductUnitTypeNameField;
        
        private decimal ReturnedCountField;
        
        private string SerialField;
        
        private decimal TotalDiscountField;
        
        private decimal TotalTollField;
        
        private decimal TotalUnitPriceField;
        
        private decimal TotalVatField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BaseUnitPrice
        {
            get
            {
                return this.BaseUnitPriceField;
            }
            set
            {
                this.BaseUnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailDescription
        {
            get
            {
                return this.DetailDescriptionField;
            }
            set
            {
                this.DetailDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DiscountPercent
        {
            get
            {
                return this.DiscountPercentField;
            }
            set
            {
                this.DiscountPercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FinalUnitPrice
        {
            get
            {
                return this.FinalUnitPriceField;
            }
            set
            {
                this.FinalUnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventoryCode
        {
            get
            {
                return this.InventoryCodeField;
            }
            set
            {
                this.InventoryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventoryName
        {
            get
            {
                return this.InventoryNameField;
            }
            set
            {
                this.InventoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty0
        {
            get
            {
                return this.InvoiceProperty0Field;
            }
            set
            {
                this.InvoiceProperty0Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty1
        {
            get
            {
                return this.InvoiceProperty1Field;
            }
            set
            {
                this.InvoiceProperty1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty10
        {
            get
            {
                return this.InvoiceProperty10Field;
            }
            set
            {
                this.InvoiceProperty10Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty2
        {
            get
            {
                return this.InvoiceProperty2Field;
            }
            set
            {
                this.InvoiceProperty2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty3
        {
            get
            {
                return this.InvoiceProperty3Field;
            }
            set
            {
                this.InvoiceProperty3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty4
        {
            get
            {
                return this.InvoiceProperty4Field;
            }
            set
            {
                this.InvoiceProperty4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty5
        {
            get
            {
                return this.InvoiceProperty5Field;
            }
            set
            {
                this.InvoiceProperty5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty6
        {
            get
            {
                return this.InvoiceProperty6Field;
            }
            set
            {
                this.InvoiceProperty6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty7
        {
            get
            {
                return this.InvoiceProperty7Field;
            }
            set
            {
                this.InvoiceProperty7Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty8
        {
            get
            {
                return this.InvoiceProperty8Field;
            }
            set
            {
                this.InvoiceProperty8Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty9
        {
            get
            {
                return this.InvoiceProperty9Field;
            }
            set
            {
                this.InvoiceProperty9Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsService
        {
            get
            {
                return this.IsServiceField;
            }
            set
            {
                this.IsServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductUnitTypeName
        {
            get
            {
                return this.ProductUnitTypeNameField;
            }
            set
            {
                this.ProductUnitTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReturnedCount
        {
            get
            {
                return this.ReturnedCountField;
            }
            set
            {
                this.ReturnedCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial
        {
            get
            {
                return this.SerialField;
            }
            set
            {
                this.SerialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDiscount
        {
            get
            {
                return this.TotalDiscountField;
            }
            set
            {
                this.TotalDiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalToll
        {
            get
            {
                return this.TotalTollField;
            }
            set
            {
                this.TotalTollField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalUnitPrice
        {
            get
            {
                return this.TotalUnitPriceField;
            }
            set
            {
                this.TotalUnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalVat
        {
            get
            {
                return this.TotalVatField;
            }
            set
            {
                this.TotalVatField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnInvoiceDetailInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class ReturnInvoiceDetailInfo : object
    {
        
        private decimal BaseUnitPriceField;
        
        private decimal CountField;
        
        private string DetailDescriptionField;
        
        private System.Nullable<decimal> DiscountCountField;
        
        private decimal FinalUnitPriceField;
        
        private int IdField;
        
        private string InvoiceProperty0Field;
        
        private string InvoiceProperty1Field;
        
        private string InvoiceProperty10Field;
        
        private string InvoiceProperty2Field;
        
        private string InvoiceProperty3Field;
        
        private string InvoiceProperty4Field;
        
        private string InvoiceProperty5Field;
        
        private string InvoiceProperty6Field;
        
        private string InvoiceProperty7Field;
        
        private string InvoiceProperty8Field;
        
        private string InvoiceProperty9Field;
        
        private string ProductCodeField;
        
        private string ProductNameField;
        
        private PgInvoiceService.RelatedReturnInvoiceDetailInfo[] RelatedInvoicesField;
        
        private string SerialField;
        
        private decimal TotalDiscountField;
        
        private decimal TotalTollField;
        
        private decimal TotalUnitPriceField;
        
        private decimal TotalVatField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BaseUnitPrice
        {
            get
            {
                return this.BaseUnitPriceField;
            }
            set
            {
                this.BaseUnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailDescription
        {
            get
            {
                return this.DetailDescriptionField;
            }
            set
            {
                this.DetailDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DiscountCount
        {
            get
            {
                return this.DiscountCountField;
            }
            set
            {
                this.DiscountCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FinalUnitPrice
        {
            get
            {
                return this.FinalUnitPriceField;
            }
            set
            {
                this.FinalUnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty0
        {
            get
            {
                return this.InvoiceProperty0Field;
            }
            set
            {
                this.InvoiceProperty0Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty1
        {
            get
            {
                return this.InvoiceProperty1Field;
            }
            set
            {
                this.InvoiceProperty1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty10
        {
            get
            {
                return this.InvoiceProperty10Field;
            }
            set
            {
                this.InvoiceProperty10Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty2
        {
            get
            {
                return this.InvoiceProperty2Field;
            }
            set
            {
                this.InvoiceProperty2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty3
        {
            get
            {
                return this.InvoiceProperty3Field;
            }
            set
            {
                this.InvoiceProperty3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty4
        {
            get
            {
                return this.InvoiceProperty4Field;
            }
            set
            {
                this.InvoiceProperty4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty5
        {
            get
            {
                return this.InvoiceProperty5Field;
            }
            set
            {
                this.InvoiceProperty5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty6
        {
            get
            {
                return this.InvoiceProperty6Field;
            }
            set
            {
                this.InvoiceProperty6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty7
        {
            get
            {
                return this.InvoiceProperty7Field;
            }
            set
            {
                this.InvoiceProperty7Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty8
        {
            get
            {
                return this.InvoiceProperty8Field;
            }
            set
            {
                this.InvoiceProperty8Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceProperty9
        {
            get
            {
                return this.InvoiceProperty9Field;
            }
            set
            {
                this.InvoiceProperty9Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgInvoiceService.RelatedReturnInvoiceDetailInfo[] RelatedInvoices
        {
            get
            {
                return this.RelatedInvoicesField;
            }
            set
            {
                this.RelatedInvoicesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial
        {
            get
            {
                return this.SerialField;
            }
            set
            {
                this.SerialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDiscount
        {
            get
            {
                return this.TotalDiscountField;
            }
            set
            {
                this.TotalDiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalToll
        {
            get
            {
                return this.TotalTollField;
            }
            set
            {
                this.TotalTollField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalUnitPrice
        {
            get
            {
                return this.TotalUnitPriceField;
            }
            set
            {
                this.TotalUnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalVat
        {
            get
            {
                return this.TotalVatField;
            }
            set
            {
                this.TotalVatField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedReturnInvoiceDetailInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class RelatedReturnInvoiceDetailInfo : object
    {
        
        private PgInvoiceService.RelatedInvoiceInfo RelatedInvoiceInfoField;
        
        private decimal ReturnedCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgInvoiceService.RelatedInvoiceInfo RelatedInvoiceInfo
        {
            get
            {
                return this.RelatedInvoiceInfoField;
            }
            set
            {
                this.RelatedInvoiceInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReturnedCount
        {
            get
            {
                return this.ReturnedCountField;
            }
            set
            {
                this.ReturnedCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedInvoiceInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class RelatedInvoiceInfo : object
    {
        
        private System.Nullable<System.Guid> RelatedInvoiceIdField;
        
        private string RelatedInvoiceNumberField;
        
        private string RelatedInvoiceTypeCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> RelatedInvoiceId
        {
            get
            {
                return this.RelatedInvoiceIdField;
            }
            set
            {
                this.RelatedInvoiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedInvoiceNumber
        {
            get
            {
                return this.RelatedInvoiceNumberField;
            }
            set
            {
                this.RelatedInvoiceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedInvoiceTypeCode
        {
            get
            {
                return this.RelatedInvoiceTypeCodeField;
            }
            set
            {
                this.RelatedInvoiceTypeCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgInvoiceService.InvoiceInfoResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgInvoiceService.SaveCrmObjectResult))]
    public partial class OperationResult : object
    {
        
        private string MessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceInfoResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class InvoiceInfoResult : PgInvoiceService.OperationResult
    {
        
        private PgInvoiceService.InvoiceInfo InvoiceInfoField;
        
        private PgInvoiceService.InvoiceInfo[] InvoiceInfoListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgInvoiceService.InvoiceInfo InvoiceInfo
        {
            get
            {
                return this.InvoiceInfoField;
            }
            set
            {
                this.InvoiceInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgInvoiceService.InvoiceInfo[] InvoiceInfoList
        {
            get
            {
                return this.InvoiceInfoListField;
            }
            set
            {
                this.InvoiceInfoListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveCrmObjectResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class SaveCrmObjectResult : PgInvoiceService.OperationResult
    {
        
        private System.Guid CrmIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CrmId
        {
            get
            {
                return this.CrmIdField;
            }
            set
            {
                this.CrmIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gp_InvoiceType", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.Domain.Model")]
    public enum Gp_InvoiceType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quote = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectDeleteOption", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.Domain.Model")]
    public enum CrmObjectDeleteOption : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssignChildrenToParent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteChildren = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nothing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeletePersons = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteWithHistory = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PgInvoiceService.IInvoice")]
    public interface IInvoice
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SaveInvoice", ReplyAction="http://tempuri.org/IInvoice/SaveInvoiceResponse")]
        PgInvoiceService.SaveCrmObjectResult SaveInvoice(string userName, string password, PgInvoiceService.InvoiceInfo invoiceInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SaveInvoice", ReplyAction="http://tempuri.org/IInvoice/SaveInvoiceResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> SaveInvoiceAsync(string userName, string password, PgInvoiceService.InvoiceInfo invoiceInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SaveReturnInvoice", ReplyAction="http://tempuri.org/IInvoice/SaveReturnInvoiceResponse")]
        PgInvoiceService.SaveCrmObjectResult SaveReturnInvoice(string userName, string password, PgInvoiceService.ReturnInvoiceInfo returnInvoiceInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SaveReturnInvoice", ReplyAction="http://tempuri.org/IInvoice/SaveReturnInvoiceResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> SaveReturnInvoiceAsync(string userName, string password, PgInvoiceService.ReturnInvoiceInfo returnInvoiceInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindInvoiceById", ReplyAction="http://tempuri.org/IInvoice/FindInvoiceByIdResponse")]
        PgInvoiceService.InvoiceInfoResult FindInvoiceById(string userName, string password, System.Guid invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindInvoiceById", ReplyAction="http://tempuri.org/IInvoice/FindInvoiceByIdResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindInvoiceByIdAsync(string userName, string password, System.Guid invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindPurchaseInvoiceById", ReplyAction="http://tempuri.org/IInvoice/FindPurchaseInvoiceByIdResponse")]
        PgInvoiceService.InvoiceInfoResult FindPurchaseInvoiceById(string userName, string password, System.Guid purchInvoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindPurchaseInvoiceById", ReplyAction="http://tempuri.org/IInvoice/FindPurchaseInvoiceByIdResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindPurchaseInvoiceByIdAsync(string userName, string password, System.Guid purchInvoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindReturnPurchaseInvoiceById", ReplyAction="http://tempuri.org/IInvoice/FindReturnPurchaseInvoiceByIdResponse")]
        PgInvoiceService.InvoiceInfoResult FindReturnPurchaseInvoiceById(string userName, string password, System.Guid retPurchInvoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindReturnPurchaseInvoiceById", ReplyAction="http://tempuri.org/IInvoice/FindReturnPurchaseInvoiceByIdResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindReturnPurchaseInvoiceByIdAsync(string userName, string password, System.Guid retPurchInvoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindQuoteById", ReplyAction="http://tempuri.org/IInvoice/FindQuoteByIdResponse")]
        PgInvoiceService.InvoiceInfoResult FindQuoteById(string userName, string password, System.Guid quoteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindQuoteById", ReplyAction="http://tempuri.org/IInvoice/FindQuoteByIdResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindQuoteByIdAsync(string userName, string password, System.Guid quoteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindPurchaseQuoteById", ReplyAction="http://tempuri.org/IInvoice/FindPurchaseQuoteByIdResponse")]
        PgInvoiceService.InvoiceInfoResult FindPurchaseQuoteById(string userName, string password, System.Guid purchaseQuoteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindPurchaseQuoteById", ReplyAction="http://tempuri.org/IInvoice/FindPurchaseQuoteByIdResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindPurchaseQuoteByIdAsync(string userName, string password, System.Guid purchaseQuoteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindReturnInvoiceById", ReplyAction="http://tempuri.org/IInvoice/FindReturnInvoiceByIdResponse")]
        PgInvoiceService.InvoiceInfoResult FindReturnInvoiceById(string userName, string password, System.Guid retInvoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindReturnInvoiceById", ReplyAction="http://tempuri.org/IInvoice/FindReturnInvoiceByIdResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindReturnInvoiceByIdAsync(string userName, string password, System.Guid retInvoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindInvoiceByNumber", ReplyAction="http://tempuri.org/IInvoice/FindInvoiceByNumberResponse")]
        PgInvoiceService.InvoiceInfoResult FindInvoiceByNumber(string userName, string password, string number, PgInvoiceService.Gp_InvoiceType invoiceType, string typeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindInvoiceByNumber", ReplyAction="http://tempuri.org/IInvoice/FindInvoiceByNumberResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindInvoiceByNumberAsync(string userName, string password, string number, PgInvoiceService.Gp_InvoiceType invoiceType, string typeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindReturnInvoiceByNumber", ReplyAction="http://tempuri.org/IInvoice/FindReturnInvoiceByNumberResponse")]
        PgInvoiceService.InvoiceInfoResult FindReturnInvoiceByNumber(string userName, string password, string number, string typeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/FindReturnInvoiceByNumber", ReplyAction="http://tempuri.org/IInvoice/FindReturnInvoiceByNumberResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindReturnInvoiceByNumberAsync(string userName, string password, string number, string typeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/DeleteInvoiceById", ReplyAction="http://tempuri.org/IInvoice/DeleteInvoiceByIdResponse")]
        PgInvoiceService.SaveCrmObjectResult DeleteInvoiceById(string userName, string password, System.Guid invoiceId, PgInvoiceService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/DeleteInvoiceById", ReplyAction="http://tempuri.org/IInvoice/DeleteInvoiceByIdResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> DeleteInvoiceByIdAsync(string userName, string password, System.Guid invoiceId, PgInvoiceService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/DeleteInvoiceByNumber", ReplyAction="http://tempuri.org/IInvoice/DeleteInvoiceByNumberResponse")]
        PgInvoiceService.InvoiceInfoResult DeleteInvoiceByNumber(string userName, string password, string number, PgInvoiceService.Gp_InvoiceType invoiceType, string typeCode, PgInvoiceService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/DeleteInvoiceByNumber", ReplyAction="http://tempuri.org/IInvoice/DeleteInvoiceByNumberResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> DeleteInvoiceByNumberAsync(string userName, string password, string number, PgInvoiceService.Gp_InvoiceType invoiceType, string typeCode, PgInvoiceService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/DeleteReturnInvoiceByNumber", ReplyAction="http://tempuri.org/IInvoice/DeleteReturnInvoiceByNumberResponse")]
        PgInvoiceService.InvoiceInfoResult DeleteReturnInvoiceByNumber(string userName, string password, string number, string typeCode, PgInvoiceService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/DeleteReturnInvoiceByNumber", ReplyAction="http://tempuri.org/IInvoice/DeleteReturnInvoiceByNumberResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> DeleteReturnInvoiceByNumberAsync(string userName, string password, string number, string typeCode, PgInvoiceService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SearchInvoice", ReplyAction="http://tempuri.org/IInvoice/SearchInvoiceResponse")]
        PgInvoiceService.InvoiceInfoResult SearchInvoice(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SearchInvoice", ReplyAction="http://tempuri.org/IInvoice/SearchInvoiceResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> SearchInvoiceAsync(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SearchQuote", ReplyAction="http://tempuri.org/IInvoice/SearchQuoteResponse")]
        PgInvoiceService.InvoiceInfoResult SearchQuote(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SearchQuote", ReplyAction="http://tempuri.org/IInvoice/SearchQuoteResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> SearchQuoteAsync(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SearchPurchaseInvoice", ReplyAction="http://tempuri.org/IInvoice/SearchPurchaseInvoiceResponse")]
        PgInvoiceService.InvoiceInfoResult SearchPurchaseInvoice(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SearchPurchaseInvoice", ReplyAction="http://tempuri.org/IInvoice/SearchPurchaseInvoiceResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> SearchPurchaseInvoiceAsync(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SearchReturnPurchaseInvoice", ReplyAction="http://tempuri.org/IInvoice/SearchReturnPurchaseInvoiceResponse")]
        PgInvoiceService.InvoiceInfoResult SearchReturnPurchaseInvoice(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SearchReturnPurchaseInvoice", ReplyAction="http://tempuri.org/IInvoice/SearchReturnPurchaseInvoiceResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> SearchReturnPurchaseInvoiceAsync(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SearchReturnSaleInvoice", ReplyAction="http://tempuri.org/IInvoice/SearchReturnSaleInvoiceResponse")]
        PgInvoiceService.InvoiceInfoResult SearchReturnSaleInvoice(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SearchReturnSaleInvoice", ReplyAction="http://tempuri.org/IInvoice/SearchReturnSaleInvoiceResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> SearchReturnSaleInvoiceAsync(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SearchPurchaseQuote", ReplyAction="http://tempuri.org/IInvoice/SearchPurchaseQuoteResponse")]
        PgInvoiceService.InvoiceInfoResult SearchPurchaseQuote(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/SearchPurchaseQuote", ReplyAction="http://tempuri.org/IInvoice/SearchPurchaseQuoteResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> SearchPurchaseQuoteAsync(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/GetInvoicesByIdentityId", ReplyAction="http://tempuri.org/IInvoice/GetInvoicesByIdentityIdResponse")]
        PgInvoiceService.InvoiceInfoResult GetInvoicesByIdentityId(string userName, string password, System.Guid identityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/GetInvoicesByIdentityId", ReplyAction="http://tempuri.org/IInvoice/GetInvoicesByIdentityIdResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> GetInvoicesByIdentityIdAsync(string userName, string password, System.Guid identityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/Approved", ReplyAction="http://tempuri.org/IInvoice/ApprovedResponse")]
        PgInvoiceService.SaveCrmObjectResult Approved(string userName, string password, System.Guid invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/Approved", ReplyAction="http://tempuri.org/IInvoice/ApprovedResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> ApprovedAsync(string userName, string password, System.Guid invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/Rejected", ReplyAction="http://tempuri.org/IInvoice/RejectedResponse")]
        PgInvoiceService.SaveCrmObjectResult Rejected(string userName, string password, System.Guid invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/Rejected", ReplyAction="http://tempuri.org/IInvoice/RejectedResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> RejectedAsync(string userName, string password, System.Guid invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/Pending", ReplyAction="http://tempuri.org/IInvoice/PendingResponse")]
        PgInvoiceService.SaveCrmObjectResult Pending(string userName, string password, System.Guid invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/Pending", ReplyAction="http://tempuri.org/IInvoice/PendingResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> PendingAsync(string userName, string password, System.Guid invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/Numbered", ReplyAction="http://tempuri.org/IInvoice/NumberedResponse")]
        PgInvoiceService.SaveCrmObjectResult Numbered(string userName, string password, System.Guid invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoice/Numbered", ReplyAction="http://tempuri.org/IInvoice/NumberedResponse")]
        System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> NumberedAsync(string userName, string password, System.Guid invoiceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IInvoiceChannel : PgInvoiceService.IInvoice, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class InvoiceClient : System.ServiceModel.ClientBase<PgInvoiceService.IInvoice>, PgInvoiceService.IInvoice
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InvoiceClient() : 
                base(InvoiceClient.GetDefaultBinding(), InvoiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IInvoice.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvoiceClient(EndpointConfiguration endpointConfiguration) : 
                base(InvoiceClient.GetBindingForEndpoint(endpointConfiguration), InvoiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvoiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InvoiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvoiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InvoiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InvoiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PgInvoiceService.SaveCrmObjectResult SaveInvoice(string userName, string password, PgInvoiceService.InvoiceInfo invoiceInfo)
        {
            return base.Channel.SaveInvoice(userName, password, invoiceInfo);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> SaveInvoiceAsync(string userName, string password, PgInvoiceService.InvoiceInfo invoiceInfo)
        {
            return base.Channel.SaveInvoiceAsync(userName, password, invoiceInfo);
        }
        
        public PgInvoiceService.SaveCrmObjectResult SaveReturnInvoice(string userName, string password, PgInvoiceService.ReturnInvoiceInfo returnInvoiceInfo)
        {
            return base.Channel.SaveReturnInvoice(userName, password, returnInvoiceInfo);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> SaveReturnInvoiceAsync(string userName, string password, PgInvoiceService.ReturnInvoiceInfo returnInvoiceInfo)
        {
            return base.Channel.SaveReturnInvoiceAsync(userName, password, returnInvoiceInfo);
        }
        
        public PgInvoiceService.InvoiceInfoResult FindInvoiceById(string userName, string password, System.Guid invoiceId)
        {
            return base.Channel.FindInvoiceById(userName, password, invoiceId);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindInvoiceByIdAsync(string userName, string password, System.Guid invoiceId)
        {
            return base.Channel.FindInvoiceByIdAsync(userName, password, invoiceId);
        }
        
        public PgInvoiceService.InvoiceInfoResult FindPurchaseInvoiceById(string userName, string password, System.Guid purchInvoiceId)
        {
            return base.Channel.FindPurchaseInvoiceById(userName, password, purchInvoiceId);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindPurchaseInvoiceByIdAsync(string userName, string password, System.Guid purchInvoiceId)
        {
            return base.Channel.FindPurchaseInvoiceByIdAsync(userName, password, purchInvoiceId);
        }
        
        public PgInvoiceService.InvoiceInfoResult FindReturnPurchaseInvoiceById(string userName, string password, System.Guid retPurchInvoiceId)
        {
            return base.Channel.FindReturnPurchaseInvoiceById(userName, password, retPurchInvoiceId);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindReturnPurchaseInvoiceByIdAsync(string userName, string password, System.Guid retPurchInvoiceId)
        {
            return base.Channel.FindReturnPurchaseInvoiceByIdAsync(userName, password, retPurchInvoiceId);
        }
        
        public PgInvoiceService.InvoiceInfoResult FindQuoteById(string userName, string password, System.Guid quoteId)
        {
            return base.Channel.FindQuoteById(userName, password, quoteId);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindQuoteByIdAsync(string userName, string password, System.Guid quoteId)
        {
            return base.Channel.FindQuoteByIdAsync(userName, password, quoteId);
        }
        
        public PgInvoiceService.InvoiceInfoResult FindPurchaseQuoteById(string userName, string password, System.Guid purchaseQuoteId)
        {
            return base.Channel.FindPurchaseQuoteById(userName, password, purchaseQuoteId);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindPurchaseQuoteByIdAsync(string userName, string password, System.Guid purchaseQuoteId)
        {
            return base.Channel.FindPurchaseQuoteByIdAsync(userName, password, purchaseQuoteId);
        }
        
        public PgInvoiceService.InvoiceInfoResult FindReturnInvoiceById(string userName, string password, System.Guid retInvoiceId)
        {
            return base.Channel.FindReturnInvoiceById(userName, password, retInvoiceId);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindReturnInvoiceByIdAsync(string userName, string password, System.Guid retInvoiceId)
        {
            return base.Channel.FindReturnInvoiceByIdAsync(userName, password, retInvoiceId);
        }
        
        public PgInvoiceService.InvoiceInfoResult FindInvoiceByNumber(string userName, string password, string number, PgInvoiceService.Gp_InvoiceType invoiceType, string typeCode)
        {
            return base.Channel.FindInvoiceByNumber(userName, password, number, invoiceType, typeCode);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindInvoiceByNumberAsync(string userName, string password, string number, PgInvoiceService.Gp_InvoiceType invoiceType, string typeCode)
        {
            return base.Channel.FindInvoiceByNumberAsync(userName, password, number, invoiceType, typeCode);
        }
        
        public PgInvoiceService.InvoiceInfoResult FindReturnInvoiceByNumber(string userName, string password, string number, string typeCode)
        {
            return base.Channel.FindReturnInvoiceByNumber(userName, password, number, typeCode);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> FindReturnInvoiceByNumberAsync(string userName, string password, string number, string typeCode)
        {
            return base.Channel.FindReturnInvoiceByNumberAsync(userName, password, number, typeCode);
        }
        
        public PgInvoiceService.SaveCrmObjectResult DeleteInvoiceById(string userName, string password, System.Guid invoiceId, PgInvoiceService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteInvoiceById(userName, password, invoiceId, deleteOption);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> DeleteInvoiceByIdAsync(string userName, string password, System.Guid invoiceId, PgInvoiceService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteInvoiceByIdAsync(userName, password, invoiceId, deleteOption);
        }
        
        public PgInvoiceService.InvoiceInfoResult DeleteInvoiceByNumber(string userName, string password, string number, PgInvoiceService.Gp_InvoiceType invoiceType, string typeCode, PgInvoiceService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteInvoiceByNumber(userName, password, number, invoiceType, typeCode, deleteOption);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> DeleteInvoiceByNumberAsync(string userName, string password, string number, PgInvoiceService.Gp_InvoiceType invoiceType, string typeCode, PgInvoiceService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteInvoiceByNumberAsync(userName, password, number, invoiceType, typeCode, deleteOption);
        }
        
        public PgInvoiceService.InvoiceInfoResult DeleteReturnInvoiceByNumber(string userName, string password, string number, string typeCode, PgInvoiceService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteReturnInvoiceByNumber(userName, password, number, typeCode, deleteOption);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> DeleteReturnInvoiceByNumberAsync(string userName, string password, string number, string typeCode, PgInvoiceService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteReturnInvoiceByNumberAsync(userName, password, number, typeCode, deleteOption);
        }
        
        public PgInvoiceService.InvoiceInfoResult SearchInvoice(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchInvoice(userName, password, typeKey, query);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> SearchInvoiceAsync(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchInvoiceAsync(userName, password, typeKey, query);
        }
        
        public PgInvoiceService.InvoiceInfoResult SearchQuote(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchQuote(userName, password, typeKey, query);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> SearchQuoteAsync(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchQuoteAsync(userName, password, typeKey, query);
        }
        
        public PgInvoiceService.InvoiceInfoResult SearchPurchaseInvoice(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchPurchaseInvoice(userName, password, typeKey, query);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> SearchPurchaseInvoiceAsync(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchPurchaseInvoiceAsync(userName, password, typeKey, query);
        }
        
        public PgInvoiceService.InvoiceInfoResult SearchReturnPurchaseInvoice(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchReturnPurchaseInvoice(userName, password, typeKey, query);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> SearchReturnPurchaseInvoiceAsync(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchReturnPurchaseInvoiceAsync(userName, password, typeKey, query);
        }
        
        public PgInvoiceService.InvoiceInfoResult SearchReturnSaleInvoice(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchReturnSaleInvoice(userName, password, typeKey, query);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> SearchReturnSaleInvoiceAsync(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchReturnSaleInvoiceAsync(userName, password, typeKey, query);
        }
        
        public PgInvoiceService.InvoiceInfoResult SearchPurchaseQuote(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchPurchaseQuote(userName, password, typeKey, query);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> SearchPurchaseQuoteAsync(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchPurchaseQuoteAsync(userName, password, typeKey, query);
        }
        
        public PgInvoiceService.InvoiceInfoResult GetInvoicesByIdentityId(string userName, string password, System.Guid identityId)
        {
            return base.Channel.GetInvoicesByIdentityId(userName, password, identityId);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.InvoiceInfoResult> GetInvoicesByIdentityIdAsync(string userName, string password, System.Guid identityId)
        {
            return base.Channel.GetInvoicesByIdentityIdAsync(userName, password, identityId);
        }
        
        public PgInvoiceService.SaveCrmObjectResult Approved(string userName, string password, System.Guid invoiceId)
        {
            return base.Channel.Approved(userName, password, invoiceId);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> ApprovedAsync(string userName, string password, System.Guid invoiceId)
        {
            return base.Channel.ApprovedAsync(userName, password, invoiceId);
        }
        
        public PgInvoiceService.SaveCrmObjectResult Rejected(string userName, string password, System.Guid invoiceId)
        {
            return base.Channel.Rejected(userName, password, invoiceId);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> RejectedAsync(string userName, string password, System.Guid invoiceId)
        {
            return base.Channel.RejectedAsync(userName, password, invoiceId);
        }
        
        public PgInvoiceService.SaveCrmObjectResult Pending(string userName, string password, System.Guid invoiceId)
        {
            return base.Channel.Pending(userName, password, invoiceId);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> PendingAsync(string userName, string password, System.Guid invoiceId)
        {
            return base.Channel.PendingAsync(userName, password, invoiceId);
        }
        
        public PgInvoiceService.SaveCrmObjectResult Numbered(string userName, string password, System.Guid invoiceId)
        {
            return base.Channel.Numbered(userName, password, invoiceId);
        }
        
        public System.Threading.Tasks.Task<PgInvoiceService.SaveCrmObjectResult> NumberedAsync(string userName, string password, System.Guid invoiceId)
        {
            return base.Channel.NumberedAsync(userName, password, invoiceId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IInvoice))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IInvoice))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.11.9/Services/API/IInvoice.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InvoiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IInvoice);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InvoiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IInvoice);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IInvoice,
        }
    }
}
