//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgMoneyAccountService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgMoneyAccountService.MoneyAccountDetailInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgMoneyAccountService.MoneyAccountListInfo))]
    public partial class OperationResult : object
    {
        
        private string MessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoneyAccountDetailInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class MoneyAccountDetailInfo : PgMoneyAccountService.OperationResult
    {
        
        private string AccountNumberField;
        
        private System.Nullable<PgMoneyAccountService.IdentityType> AccountOwnerIdentityTypeField;
        
        private string AccountOwnerNameField;
        
        private string ApiKeyField;
        
        private string BankNameField;
        
        private string BankTypeKeyField;
        
        private string CardNumberField;
        
        private PgMoneyAccountService.MoneyAccountType MoneyAccountTypeField;
        
        private string NameField;
        
        private System.Nullable<PgMoneyAccountService.OnlinePaymentControllerType> OnlinePaymentControllerTypeField;
        
        private string OtherData1Field;
        
        private string OtherData2Field;
        
        private string PasswordField;
        
        private bool SupportsCardToCardPaymentField;
        
        private bool SupportsCashPaymentField;
        
        private bool SupportsOnlinePaymentField;
        
        private string UserKeyField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<PgMoneyAccountService.IdentityType> AccountOwnerIdentityType
        {
            get
            {
                return this.AccountOwnerIdentityTypeField;
            }
            set
            {
                this.AccountOwnerIdentityTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountOwnerName
        {
            get
            {
                return this.AccountOwnerNameField;
            }
            set
            {
                this.AccountOwnerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApiKey
        {
            get
            {
                return this.ApiKeyField;
            }
            set
            {
                this.ApiKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName
        {
            get
            {
                return this.BankNameField;
            }
            set
            {
                this.BankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankTypeKey
        {
            get
            {
                return this.BankTypeKeyField;
            }
            set
            {
                this.BankTypeKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgMoneyAccountService.MoneyAccountType MoneyAccountType
        {
            get
            {
                return this.MoneyAccountTypeField;
            }
            set
            {
                this.MoneyAccountTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<PgMoneyAccountService.OnlinePaymentControllerType> OnlinePaymentControllerType
        {
            get
            {
                return this.OnlinePaymentControllerTypeField;
            }
            set
            {
                this.OnlinePaymentControllerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherData1
        {
            get
            {
                return this.OtherData1Field;
            }
            set
            {
                this.OtherData1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherData2
        {
            get
            {
                return this.OtherData2Field;
            }
            set
            {
                this.OtherData2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportsCardToCardPayment
        {
            get
            {
                return this.SupportsCardToCardPaymentField;
            }
            set
            {
                this.SupportsCardToCardPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportsCashPayment
        {
            get
            {
                return this.SupportsCashPaymentField;
            }
            set
            {
                this.SupportsCashPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportsOnlinePayment
        {
            get
            {
                return this.SupportsOnlinePaymentField;
            }
            set
            {
                this.SupportsOnlinePaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoneyAccountListInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class MoneyAccountListInfo : PgMoneyAccountService.OperationResult
    {
        
        private PgMoneyAccountService.MoneyAccountSummaryInfo[] ItemsField;
        
        private int TotalCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgMoneyAccountService.MoneyAccountSummaryInfo[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount
        {
            get
            {
                return this.TotalCountField;
            }
            set
            {
                this.TotalCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoneyAccountSummaryInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class MoneyAccountSummaryInfo : object
    {
        
        private string AccountNumberField;
        
        private System.Nullable<PgMoneyAccountService.IdentityType> AccountOwnerIdentityTypeField;
        
        private string AccountOwnerNameField;
        
        private string BankNameField;
        
        private string BankTypeKeyField;
        
        private string CardNumberField;
        
        private int IdField;
        
        private PgMoneyAccountService.MoneyAccountType MoneyAccountTypeField;
        
        private string NameField;
        
        private System.Nullable<PgMoneyAccountService.OnlinePaymentControllerType> OnlinePaymentControllerTypeField;
        
        private bool SupportsCardToCardPaymentField;
        
        private bool SupportsCashPaymentField;
        
        private bool SupportsOnlinePaymentField;
        
        private string UserKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<PgMoneyAccountService.IdentityType> AccountOwnerIdentityType
        {
            get
            {
                return this.AccountOwnerIdentityTypeField;
            }
            set
            {
                this.AccountOwnerIdentityTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountOwnerName
        {
            get
            {
                return this.AccountOwnerNameField;
            }
            set
            {
                this.AccountOwnerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName
        {
            get
            {
                return this.BankNameField;
            }
            set
            {
                this.BankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankTypeKey
        {
            get
            {
                return this.BankTypeKeyField;
            }
            set
            {
                this.BankTypeKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgMoneyAccountService.MoneyAccountType MoneyAccountType
        {
            get
            {
                return this.MoneyAccountTypeField;
            }
            set
            {
                this.MoneyAccountTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<PgMoneyAccountService.OnlinePaymentControllerType> OnlinePaymentControllerType
        {
            get
            {
                return this.OnlinePaymentControllerTypeField;
            }
            set
            {
                this.OnlinePaymentControllerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportsCardToCardPayment
        {
            get
            {
                return this.SupportsCardToCardPaymentField;
            }
            set
            {
                this.SupportsCardToCardPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportsCashPayment
        {
            get
            {
                return this.SupportsCashPaymentField;
            }
            set
            {
                this.SupportsCashPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportsOnlinePayment
        {
            get
            {
                return this.SupportsOnlinePaymentField;
            }
            set
            {
                this.SupportsOnlinePaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityType", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public enum IdentityType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Person = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Organization = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoneyAccountType", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public enum MoneyAccountType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bank = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cash = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnlinePaymentControllerType", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public enum OnlinePaymentControllerType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Saman = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pasargad = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ghavvamin = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PardakhtVaset = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PgMoneyAccountService.IMoneyAccount")]
    public interface IMoneyAccount
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoneyAccount/GetMoneyAccountList", ReplyAction="http://tempuri.org/IMoneyAccount/GetMoneyAccountListResponse")]
        PgMoneyAccountService.MoneyAccountListInfo GetMoneyAccountList(string userName, string password, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoneyAccount/GetMoneyAccountList", ReplyAction="http://tempuri.org/IMoneyAccount/GetMoneyAccountListResponse")]
        System.Threading.Tasks.Task<PgMoneyAccountService.MoneyAccountListInfo> GetMoneyAccountListAsync(string userName, string password, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoneyAccount/GetMoneyAccount", ReplyAction="http://tempuri.org/IMoneyAccount/GetMoneyAccountResponse")]
        PgMoneyAccountService.MoneyAccountDetailInfo GetMoneyAccount(string userName, string password, string userKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoneyAccount/GetMoneyAccount", ReplyAction="http://tempuri.org/IMoneyAccount/GetMoneyAccountResponse")]
        System.Threading.Tasks.Task<PgMoneyAccountService.MoneyAccountDetailInfo> GetMoneyAccountAsync(string userName, string password, string userKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IMoneyAccountChannel : PgMoneyAccountService.IMoneyAccount, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MoneyAccountClient : System.ServiceModel.ClientBase<PgMoneyAccountService.IMoneyAccount>, PgMoneyAccountService.IMoneyAccount
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MoneyAccountClient() : 
                base(MoneyAccountClient.GetDefaultBinding(), MoneyAccountClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMoneyAccount.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MoneyAccountClient(EndpointConfiguration endpointConfiguration) : 
                base(MoneyAccountClient.GetBindingForEndpoint(endpointConfiguration), MoneyAccountClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MoneyAccountClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MoneyAccountClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MoneyAccountClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MoneyAccountClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MoneyAccountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PgMoneyAccountService.MoneyAccountListInfo GetMoneyAccountList(string userName, string password, int pageIndex, int pageSize)
        {
            return base.Channel.GetMoneyAccountList(userName, password, pageIndex, pageSize);
        }
        
        public System.Threading.Tasks.Task<PgMoneyAccountService.MoneyAccountListInfo> GetMoneyAccountListAsync(string userName, string password, int pageIndex, int pageSize)
        {
            return base.Channel.GetMoneyAccountListAsync(userName, password, pageIndex, pageSize);
        }
        
        public PgMoneyAccountService.MoneyAccountDetailInfo GetMoneyAccount(string userName, string password, string userKey)
        {
            return base.Channel.GetMoneyAccount(userName, password, userKey);
        }
        
        public System.Threading.Tasks.Task<PgMoneyAccountService.MoneyAccountDetailInfo> GetMoneyAccountAsync(string userName, string password, string userKey)
        {
            return base.Channel.GetMoneyAccountAsync(userName, password, userKey);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMoneyAccount))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMoneyAccount))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.11.9/Services/API/IMoneyAccount.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MoneyAccountClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMoneyAccount);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MoneyAccountClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMoneyAccount);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMoneyAccount,
        }
    }
}
