//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgCrmObjectTypeService
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectTypes", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public enum CrmObjectTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Opportunity = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Task = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PhoneLog = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessNote = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        File = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FollowUp = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quote = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Receipt = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Appointment = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contract = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notification = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Form = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ticket = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PurchaseInvoice = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnPurchaseInvoice = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReturnSaleInvoice = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PurchaseQuote = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EnterInventoryTransaction = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExitInventoryTransaction = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InitialStockInventoryTransaction = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisposeInventoryTransaction = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Payment = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Identity = 24,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgCrmObjectTypeService.CardtableResultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgCrmObjectTypeService.CrmObjectTypeListInfo))]
    public partial class OperationResult : object
    {
        
        private string MessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardtableResultInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class CardtableResultInfo : PgCrmObjectTypeService.OperationResult
    {
        
        private PgCrmObjectTypeService.CardtableItemInfo[] CardtableItemsField;
        
        private int TotalItemsCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgCrmObjectTypeService.CardtableItemInfo[] CardtableItems
        {
            get
            {
                return this.CardtableItemsField;
            }
            set
            {
                this.CardtableItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItemsCount
        {
            get
            {
                return this.TotalItemsCountField;
            }
            set
            {
                this.TotalItemsCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectTypeListInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class CrmObjectTypeListInfo : PgCrmObjectTypeService.OperationResult
    {
        
        private PgCrmObjectTypeService.CrmObjectTypeBasicInfo[] CrmObjectTypeListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgCrmObjectTypeService.CrmObjectTypeBasicInfo[] CrmObjectTypeList
        {
            get
            {
                return this.CrmObjectTypeListField;
            }
            set
            {
                this.CrmObjectTypeListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectTypeBasicInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgCrmObjectTypeService.CrmObjectTypeInfo))]
    public partial class CrmObjectTypeBasicInfo : object
    {
        
        private bool CreateByCustomerField;
        
        private PgCrmObjectTypeService.CrmObjectTypes CrmObjectTypeField;
        
        private System.Guid IdField;
        
        private bool IsAbstractField;
        
        private bool IsActiveField;
        
        private bool IsUnderProcessField;
        
        private string NameField;
        
        private System.Nullable<System.Guid> OwnerIdField;
        
        private System.Nullable<System.Guid> ParentIdField;
        
        private bool ShowToCustomerField;
        
        private string UserKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CreateByCustomer
        {
            get
            {
                return this.CreateByCustomerField;
            }
            set
            {
                this.CreateByCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgCrmObjectTypeService.CrmObjectTypes CrmObjectType
        {
            get
            {
                return this.CrmObjectTypeField;
            }
            set
            {
                this.CrmObjectTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAbstract
        {
            get
            {
                return this.IsAbstractField;
            }
            set
            {
                this.IsAbstractField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUnderProcess
        {
            get
            {
                return this.IsUnderProcessField;
            }
            set
            {
                this.IsUnderProcessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentId
        {
            get
            {
                return this.ParentIdField;
            }
            set
            {
                this.ParentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowToCustomer
        {
            get
            {
                return this.ShowToCustomerField;
            }
            set
            {
                this.ShowToCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardtableItemInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class CardtableItemInfo : object
    {
        
        private PgCrmObjectTypeService.CardtableStatus CardtableStatusField;
        
        private System.Guid CrmObjectIdField;
        
        private System.Nullable<PgCrmObjectTypeService.CrmObjectTypes> CrmObjectTypeField;
        
        private System.Nullable<System.Guid> CrmObjectTypeIdField;
        
        private System.Nullable<System.DateTime> EnterCardtableDateField;
        
        private string EnterCardtableDateLocalizedField;
        
        private string EnterCardtableDatePersianField;
        
        private System.Nullable<System.Guid> HolderIdField;
        
        private string HolderNameField;
        
        private System.Nullable<System.Guid> IdentityIdField;
        
        private string IdentityNickNameField;
        
        private System.Guid LifePathIdField;
        
        private long ProcessInstanceIdField;
        
        private System.Nullable<PgCrmObjectTypeService.ProcessInstanceType> ProcessInstanceTypeField;
        
        private System.Nullable<PgCrmObjectTypeService.StateActionType> StateActionTypeIndexField;
        
        private System.Nullable<System.Guid> StateIdField;
        
        private string StateNameField;
        
        private string StateUserKeyField;
        
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgCrmObjectTypeService.CardtableStatus CardtableStatus
        {
            get
            {
                return this.CardtableStatusField;
            }
            set
            {
                this.CardtableStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CrmObjectId
        {
            get
            {
                return this.CrmObjectIdField;
            }
            set
            {
                this.CrmObjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<PgCrmObjectTypeService.CrmObjectTypes> CrmObjectType
        {
            get
            {
                return this.CrmObjectTypeField;
            }
            set
            {
                this.CrmObjectTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CrmObjectTypeId
        {
            get
            {
                return this.CrmObjectTypeIdField;
            }
            set
            {
                this.CrmObjectTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EnterCardtableDate
        {
            get
            {
                return this.EnterCardtableDateField;
            }
            set
            {
                this.EnterCardtableDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterCardtableDateLocalized
        {
            get
            {
                return this.EnterCardtableDateLocalizedField;
            }
            set
            {
                this.EnterCardtableDateLocalizedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterCardtableDatePersian
        {
            get
            {
                return this.EnterCardtableDatePersianField;
            }
            set
            {
                this.EnterCardtableDatePersianField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> HolderId
        {
            get
            {
                return this.HolderIdField;
            }
            set
            {
                this.HolderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HolderName
        {
            get
            {
                return this.HolderNameField;
            }
            set
            {
                this.HolderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> IdentityId
        {
            get
            {
                return this.IdentityIdField;
            }
            set
            {
                this.IdentityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityNickName
        {
            get
            {
                return this.IdentityNickNameField;
            }
            set
            {
                this.IdentityNickNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LifePathId
        {
            get
            {
                return this.LifePathIdField;
            }
            set
            {
                this.LifePathIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProcessInstanceId
        {
            get
            {
                return this.ProcessInstanceIdField;
            }
            set
            {
                this.ProcessInstanceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<PgCrmObjectTypeService.ProcessInstanceType> ProcessInstanceType
        {
            get
            {
                return this.ProcessInstanceTypeField;
            }
            set
            {
                this.ProcessInstanceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<PgCrmObjectTypeService.StateActionType> StateActionTypeIndex
        {
            get
            {
                return this.StateActionTypeIndexField;
            }
            set
            {
                this.StateActionTypeIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> StateId
        {
            get
            {
                return this.StateIdField;
            }
            set
            {
                this.StateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName
        {
            get
            {
                return this.StateNameField;
            }
            set
            {
                this.StateNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateUserKey
        {
            get
            {
                return this.StateUserKeyField;
            }
            set
            {
                this.StateUserKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardtableStatus", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public enum CardtableStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InCardTable = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Viewed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProgress = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Frezzed = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finished = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessInstanceType", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public enum ProcessInstanceType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralFlow = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Process = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FollowUp = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateActionType", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public enum StateActionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cardtable = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Decision = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendSms = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendEmail = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendFax = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendPrint = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApproveBillableObject = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Assignment = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Final = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SetOpportunityStage = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RejectBillableObject = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendHttpRequest = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApproveInventoryTransaction = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RejectInventoryTransaction = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wait = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FollowUp = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Task = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreateUser = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Membership = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Condition = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StartProcess = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BlackList = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendSocialSms = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateExternalResourceField = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Opportunity = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConvertCrmObject = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreateAppointment = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CustomerNumber = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaymentLink = 29,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectTypeInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class CrmObjectTypeInfo : PgCrmObjectTypeService.CrmObjectTypeBasicInfo
    {
        
        private string MessageField;
        
        private PgCrmObjectTypeService.PropertyGroupInfo[] PropertyGroupsField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgCrmObjectTypeService.PropertyGroupInfo[] PropertyGroups
        {
            get
            {
                return this.PropertyGroupsField;
            }
            set
            {
                this.PropertyGroupsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyGroupInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class PropertyGroupInfo : object
    {
        
        private int DisplayIndexField;
        
        private long IdField;
        
        private string NameField;
        
        private PgCrmObjectTypeService.PropertyDefinitionInfo[] PropertiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisplayIndex
        {
            get
            {
                return this.DisplayIndexField;
            }
            set
            {
                this.DisplayIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgCrmObjectTypeService.PropertyDefinitionInfo[] Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyDefinitionInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class PropertyDefinitionInfo : object
    {
        
        private System.Guid IdField;
        
        private string KeyField;
        
        private string NameField;
        
        private System.Nullable<PgCrmObjectTypeService.PropertyDisplayType> PropertyDisplayTypeField;
        
        private string UserKeyField;
        
        private PgCrmObjectTypeService.PropertyDefinitionValueInfo[] ValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<PgCrmObjectTypeService.PropertyDisplayType> PropertyDisplayType
        {
            get
            {
                return this.PropertyDisplayTypeField;
            }
            set
            {
                this.PropertyDisplayTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgCrmObjectTypeService.PropertyDefinitionValueInfo[] Values
        {
            get
            {
                return this.ValuesField;
            }
            set
            {
                this.ValuesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyDisplayType", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public enum PropertyDisplayType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DropDownList = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Date = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Checkbox = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralProperty = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Html = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        File = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Number = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Currency = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Identity = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GregorianDate = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SecurityItem = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quote = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contract = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Receipt = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Group = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Time = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Form = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductList = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InputInventoryTransaction = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Payment = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OutputInventoryTransaction = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RelatedLists = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Image = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Label = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AutoNumber = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebService = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Excel = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Appointment = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Link = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PurchaseInvoice = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PurchaseQuote = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Position = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Department = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CrmObjectMultiValue = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TextMultiValue = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NumberMultiValue = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CurrencyMultiValue = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LinkMultiValue = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersianDateMultiValue = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GregorianDateMultiValue = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FileMultiValue = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdentityMultiValue = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SecurityItemMultiValue = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserMultiValue = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GroupMultiValue = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PositionMultiValue = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DepartmentMultiValue = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PrimaryKey = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stage = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Duration = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContactAddress = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PriceList = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankAccount = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Calendar = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Room = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inventory = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceDetailContainer = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Classification = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InventoryTransactionDetailContainer = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CustomerNumber = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CrmObject = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MarketingCampaign = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Color = 66,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyDefinitionValueInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class PropertyDefinitionValueInfo : object
    {
        
        private System.Guid IdField;
        
        private int IndexField;
        
        private System.Nullable<System.Guid> ParentIdField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index
        {
            get
            {
                return this.IndexField;
            }
            set
            {
                this.IndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentId
        {
            get
            {
                return this.ParentIdField;
            }
            set
            {
                this.ParentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortOperator", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public enum SortOperator : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Asc = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Desc = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PgCrmObjectTypeService.ICrmObjectType")]
    public interface ICrmObjectType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObjectType/GetCrmObjectTypeList", ReplyAction="http://tempuri.org/ICrmObjectType/GetCrmObjectTypeListResponse")]
        PgCrmObjectTypeService.CrmObjectTypeListInfo GetCrmObjectTypeList(string username, string password, System.Nullable<PgCrmObjectTypeService.CrmObjectTypes> crmObjectTypeIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObjectType/GetCrmObjectTypeList", ReplyAction="http://tempuri.org/ICrmObjectType/GetCrmObjectTypeListResponse")]
        System.Threading.Tasks.Task<PgCrmObjectTypeService.CrmObjectTypeListInfo> GetCrmObjectTypeListAsync(string username, string password, System.Nullable<PgCrmObjectTypeService.CrmObjectTypes> crmObjectTypeIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObjectType/GetCrmObjectTypeInfo", ReplyAction="http://tempuri.org/ICrmObjectType/GetCrmObjectTypeInfoResponse")]
        PgCrmObjectTypeService.CrmObjectTypeInfo GetCrmObjectTypeInfo(string username, string password, string typeKeyOrId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObjectType/GetCrmObjectTypeInfo", ReplyAction="http://tempuri.org/ICrmObjectType/GetCrmObjectTypeInfoResponse")]
        System.Threading.Tasks.Task<PgCrmObjectTypeService.CrmObjectTypeInfo> GetCrmObjectTypeInfoAsync(string username, string password, string typeKeyOrId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObjectType/GetCardtable", ReplyAction="http://tempuri.org/ICrmObjectType/GetCardtableResponse")]
        PgCrmObjectTypeService.CardtableResultInfo GetCardtable(string username, string password, string cardtabeHolder, System.Nullable<PgCrmObjectTypeService.ProcessInstanceType> instanceType, string crmObjectTypeKey, System.Nullable<System.Guid> identityId, PgCrmObjectTypeService.SortOperator sortOperator, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObjectType/GetCardtable", ReplyAction="http://tempuri.org/ICrmObjectType/GetCardtableResponse")]
        System.Threading.Tasks.Task<PgCrmObjectTypeService.CardtableResultInfo> GetCardtableAsync(string username, string password, string cardtabeHolder, System.Nullable<PgCrmObjectTypeService.ProcessInstanceType> instanceType, string crmObjectTypeKey, System.Nullable<System.Guid> identityId, PgCrmObjectTypeService.SortOperator sortOperator, int pageIndex, int pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ICrmObjectTypeChannel : PgCrmObjectTypeService.ICrmObjectType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CrmObjectTypeClient : System.ServiceModel.ClientBase<PgCrmObjectTypeService.ICrmObjectType>, PgCrmObjectTypeService.ICrmObjectType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CrmObjectTypeClient() : 
                base(CrmObjectTypeClient.GetDefaultBinding(), CrmObjectTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICrmObjectType.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrmObjectTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(CrmObjectTypeClient.GetBindingForEndpoint(endpointConfiguration), CrmObjectTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrmObjectTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CrmObjectTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrmObjectTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CrmObjectTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrmObjectTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PgCrmObjectTypeService.CrmObjectTypeListInfo GetCrmObjectTypeList(string username, string password, System.Nullable<PgCrmObjectTypeService.CrmObjectTypes> crmObjectTypeIndex)
        {
            return base.Channel.GetCrmObjectTypeList(username, password, crmObjectTypeIndex);
        }
        
        public System.Threading.Tasks.Task<PgCrmObjectTypeService.CrmObjectTypeListInfo> GetCrmObjectTypeListAsync(string username, string password, System.Nullable<PgCrmObjectTypeService.CrmObjectTypes> crmObjectTypeIndex)
        {
            return base.Channel.GetCrmObjectTypeListAsync(username, password, crmObjectTypeIndex);
        }
        
        public PgCrmObjectTypeService.CrmObjectTypeInfo GetCrmObjectTypeInfo(string username, string password, string typeKeyOrId)
        {
            return base.Channel.GetCrmObjectTypeInfo(username, password, typeKeyOrId);
        }
        
        public System.Threading.Tasks.Task<PgCrmObjectTypeService.CrmObjectTypeInfo> GetCrmObjectTypeInfoAsync(string username, string password, string typeKeyOrId)
        {
            return base.Channel.GetCrmObjectTypeInfoAsync(username, password, typeKeyOrId);
        }
        
        public PgCrmObjectTypeService.CardtableResultInfo GetCardtable(string username, string password, string cardtabeHolder, System.Nullable<PgCrmObjectTypeService.ProcessInstanceType> instanceType, string crmObjectTypeKey, System.Nullable<System.Guid> identityId, PgCrmObjectTypeService.SortOperator sortOperator, int pageIndex, int pageSize)
        {
            return base.Channel.GetCardtable(username, password, cardtabeHolder, instanceType, crmObjectTypeKey, identityId, sortOperator, pageIndex, pageSize);
        }
        
        public System.Threading.Tasks.Task<PgCrmObjectTypeService.CardtableResultInfo> GetCardtableAsync(string username, string password, string cardtabeHolder, System.Nullable<PgCrmObjectTypeService.ProcessInstanceType> instanceType, string crmObjectTypeKey, System.Nullable<System.Guid> identityId, PgCrmObjectTypeService.SortOperator sortOperator, int pageIndex, int pageSize)
        {
            return base.Channel.GetCardtableAsync(username, password, cardtabeHolder, instanceType, crmObjectTypeKey, identityId, sortOperator, pageIndex, pageSize);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICrmObjectType))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICrmObjectType))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.11.9/Services/API/ICrmObjectType.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CrmObjectTypeClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICrmObjectType);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CrmObjectTypeClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICrmObjectType);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICrmObjectType,
        }
    }
}
