//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgEPayService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentLinkInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class PaymentLinkInfo : object
    {
        
        private decimal AmountField;
        
        private string DescriptionField;
        
        private string EmailAddressField;
        
        private short ExpireAfterDaysField;
        
        private System.Guid IdentityIdField;
        
        private string MobilePhoneNumberField;
        
        private string MoneyAccountUserKeyField;
        
        private string PaymentTypeUserKeyField;
        
        private bool RegisterReceiptField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ExpireAfterDays
        {
            get
            {
                return this.ExpireAfterDaysField;
            }
            set
            {
                this.ExpireAfterDaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdentityId
        {
            get
            {
                return this.IdentityIdField;
            }
            set
            {
                this.IdentityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhoneNumber
        {
            get
            {
                return this.MobilePhoneNumberField;
            }
            set
            {
                this.MobilePhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoneyAccountUserKey
        {
            get
            {
                return this.MoneyAccountUserKeyField;
            }
            set
            {
                this.MoneyAccountUserKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentTypeUserKey
        {
            get
            {
                return this.PaymentTypeUserKeyField;
            }
            set
            {
                this.PaymentTypeUserKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RegisterReceipt
        {
            get
            {
                return this.RegisterReceiptField;
            }
            set
            {
                this.RegisterReceiptField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgEPayService.PaymentLinkInfoResult))]
    public partial class OperationResult : object
    {
        
        private string MessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentLinkInfoResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class PaymentLinkInfoResult : PgEPayService.OperationResult
    {
        
        private string PaymentLinkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentLink
        {
            get
            {
                return this.PaymentLinkField;
            }
            set
            {
                this.PaymentLinkField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PgEPayService.IEpay")]
    public interface IEpay
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEpay/CreatePaymentLink", ReplyAction="http://tempuri.org/IEpay/CreatePaymentLinkResponse")]
        PgEPayService.PaymentLinkInfoResult CreatePaymentLink(string username, string password, PgEPayService.PaymentLinkInfo paymentLink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEpay/CreatePaymentLink", ReplyAction="http://tempuri.org/IEpay/CreatePaymentLinkResponse")]
        System.Threading.Tasks.Task<PgEPayService.PaymentLinkInfoResult> CreatePaymentLinkAsync(string username, string password, PgEPayService.PaymentLinkInfo paymentLink);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IEpayChannel : PgEPayService.IEpay, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class EpayClient : System.ServiceModel.ClientBase<PgEPayService.IEpay>, PgEPayService.IEpay
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EpayClient() : 
                base(EpayClient.GetDefaultBinding(), EpayClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEpay.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EpayClient(EndpointConfiguration endpointConfiguration) : 
                base(EpayClient.GetBindingForEndpoint(endpointConfiguration), EpayClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EpayClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EpayClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EpayClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EpayClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EpayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PgEPayService.PaymentLinkInfoResult CreatePaymentLink(string username, string password, PgEPayService.PaymentLinkInfo paymentLink)
        {
            return base.Channel.CreatePaymentLink(username, password, paymentLink);
        }
        
        public System.Threading.Tasks.Task<PgEPayService.PaymentLinkInfoResult> CreatePaymentLinkAsync(string username, string password, PgEPayService.PaymentLinkInfo paymentLink)
        {
            return base.Channel.CreatePaymentLinkAsync(username, password, paymentLink);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEpay))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEpay))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.11.9/Services/API/IEpay.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EpayClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEpay);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EpayClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEpay);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEpay,
        }
    }
}
