//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgContractService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgContractService.GeneralCrmObjectInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgContractService.BaseBillableObjectInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgContractService.ContractInfo))]
    public partial class BaseCrmObjectInfo : object
    {
        
        private System.DateTime CreatDateField;
        
        private System.Nullable<System.Guid> CrmIdField;
        
        private string CrmObjectTypeCodeField;
        
        private System.Guid CrmObjectTypeIdField;
        
        private int CrmObjectTypeIndexField;
        
        private string CrmObjectTypeNameField;
        
        private PgContractService.BaseCrmObjectExtendedPropertyInfo[] ExtendedPropertiesField;
        
        private System.DateTime ModifyDateField;
        
        private System.Nullable<System.Guid> ParentCrmObjectIdField;
        
        private System.Nullable<int> ProcessStateIndexField;
        
        private string RefIdField;
        
        private string StageField;
        
        private System.Nullable<System.Guid> StageIdField;
        
        private string[] TagsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatDate
        {
            get
            {
                return this.CreatDateField;
            }
            set
            {
                this.CreatDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CrmId
        {
            get
            {
                return this.CrmIdField;
            }
            set
            {
                this.CrmIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeCode
        {
            get
            {
                return this.CrmObjectTypeCodeField;
            }
            set
            {
                this.CrmObjectTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CrmObjectTypeId
        {
            get
            {
                return this.CrmObjectTypeIdField;
            }
            set
            {
                this.CrmObjectTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrmObjectTypeIndex
        {
            get
            {
                return this.CrmObjectTypeIndexField;
            }
            set
            {
                this.CrmObjectTypeIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeName
        {
            get
            {
                return this.CrmObjectTypeNameField;
            }
            set
            {
                this.CrmObjectTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgContractService.BaseCrmObjectExtendedPropertyInfo[] ExtendedProperties
        {
            get
            {
                return this.ExtendedPropertiesField;
            }
            set
            {
                this.ExtendedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyDate
        {
            get
            {
                return this.ModifyDateField;
            }
            set
            {
                this.ModifyDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentCrmObjectId
        {
            get
            {
                return this.ParentCrmObjectIdField;
            }
            set
            {
                this.ParentCrmObjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProcessStateIndex
        {
            get
            {
                return this.ProcessStateIndexField;
            }
            set
            {
                this.ProcessStateIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId
        {
            get
            {
                return this.RefIdField;
            }
            set
            {
                this.RefIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stage
        {
            get
            {
                return this.StageField;
            }
            set
            {
                this.StageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> StageId
        {
            get
            {
                return this.StageIdField;
            }
            set
            {
                this.StageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralCrmObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgContractService.BaseBillableObjectInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgContractService.ContractInfo))]
    public partial class GeneralCrmObjectInfo : PgContractService.BaseCrmObjectInfo
    {
        
        private string DescriptionField;
        
        private System.Nullable<System.Guid> IdentityIdField;
        
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> IdentityId
        {
            get
            {
                return this.IdentityIdField;
            }
            set
            {
                this.IdentityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseBillableObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgContractService.ContractInfo))]
    public partial class BaseBillableObjectInfo : PgContractService.GeneralCrmObjectInfo
    {
        
        private string BillableObjectStateField;
        
        private decimal FinalValueField;
        
        private string NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillableObjectState
        {
            get
            {
                return this.BillableObjectStateField;
            }
            set
            {
                this.BillableObjectStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FinalValue
        {
            get
            {
                return this.FinalValueField;
            }
            set
            {
                this.FinalValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class ContractInfo : PgContractService.BaseBillableObjectInfo
    {
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private string EndDatePersianField;
        
        private bool IsBillableField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private string StartDatePersianField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDatePersian
        {
            get
            {
                return this.EndDatePersianField;
            }
            set
            {
                this.EndDatePersianField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBillable
        {
            get
            {
                return this.IsBillableField;
            }
            set
            {
                this.IsBillableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDatePersian
        {
            get
            {
                return this.StartDatePersianField;
            }
            set
            {
                this.StartDatePersianField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectExtendedPropertyInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class BaseCrmObjectExtendedPropertyInfo : object
    {
        
        private string NameField;
        
        private string UserKeyField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgContractService.ContractInfoResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgContractService.SaveCrmObjectResult))]
    public partial class OperationResult : object
    {
        
        private string MessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractInfoResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class ContractInfoResult : PgContractService.OperationResult
    {
        
        private PgContractService.ContractInfo ContractInfoField;
        
        private PgContractService.ContractInfo[] ContractInfoListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgContractService.ContractInfo ContractInfo
        {
            get
            {
                return this.ContractInfoField;
            }
            set
            {
                this.ContractInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgContractService.ContractInfo[] ContractInfoList
        {
            get
            {
                return this.ContractInfoListField;
            }
            set
            {
                this.ContractInfoListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveCrmObjectResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class SaveCrmObjectResult : PgContractService.OperationResult
    {
        
        private System.Guid CrmIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CrmId
        {
            get
            {
                return this.CrmIdField;
            }
            set
            {
                this.CrmIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectDeleteOption", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.Domain.Model")]
    public enum CrmObjectDeleteOption : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssignChildrenToParent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteChildren = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nothing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeletePersons = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteWithHistory = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PgContractService.IContract")]
    public interface IContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/SaveContract", ReplyAction="http://tempuri.org/IContract/SaveContractResponse")]
        PgContractService.SaveCrmObjectResult SaveContract(string userName, string password, PgContractService.ContractInfo contractInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/SaveContract", ReplyAction="http://tempuri.org/IContract/SaveContractResponse")]
        System.Threading.Tasks.Task<PgContractService.SaveCrmObjectResult> SaveContractAsync(string userName, string password, PgContractService.ContractInfo contractInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/SearchContract", ReplyAction="http://tempuri.org/IContract/SearchContractResponse")]
        PgContractService.ContractInfoResult SearchContract(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/SearchContract", ReplyAction="http://tempuri.org/IContract/SearchContractResponse")]
        System.Threading.Tasks.Task<PgContractService.ContractInfoResult> SearchContractAsync(string userName, string password, string typeKey, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/FindContractById", ReplyAction="http://tempuri.org/IContract/FindContractByIdResponse")]
        PgContractService.ContractInfoResult FindContractById(string userName, string password, System.Guid contractId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/FindContractById", ReplyAction="http://tempuri.org/IContract/FindContractByIdResponse")]
        System.Threading.Tasks.Task<PgContractService.ContractInfoResult> FindContractByIdAsync(string userName, string password, System.Guid contractId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/DeleteContractById", ReplyAction="http://tempuri.org/IContract/DeleteContractByIdResponse")]
        PgContractService.SaveCrmObjectResult DeleteContractById(string userName, string password, System.Guid contractId, PgContractService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/DeleteContractById", ReplyAction="http://tempuri.org/IContract/DeleteContractByIdResponse")]
        System.Threading.Tasks.Task<PgContractService.SaveCrmObjectResult> DeleteContractByIdAsync(string userName, string password, System.Guid contractId, PgContractService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/ApprovedContract", ReplyAction="http://tempuri.org/IContract/ApprovedContractResponse")]
        PgContractService.SaveCrmObjectResult ApprovedContract(string userName, string password, System.Guid contractId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/ApprovedContract", ReplyAction="http://tempuri.org/IContract/ApprovedContractResponse")]
        System.Threading.Tasks.Task<PgContractService.SaveCrmObjectResult> ApprovedContractAsync(string userName, string password, System.Guid contractId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/RejectedContract", ReplyAction="http://tempuri.org/IContract/RejectedContractResponse")]
        PgContractService.SaveCrmObjectResult RejectedContract(string userName, string password, System.Guid contractId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/RejectedContract", ReplyAction="http://tempuri.org/IContract/RejectedContractResponse")]
        System.Threading.Tasks.Task<PgContractService.SaveCrmObjectResult> RejectedContractAsync(string userName, string password, System.Guid contractId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/PendingContract", ReplyAction="http://tempuri.org/IContract/PendingContractResponse")]
        PgContractService.SaveCrmObjectResult PendingContract(string userName, string password, System.Guid contractId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/PendingContract", ReplyAction="http://tempuri.org/IContract/PendingContractResponse")]
        System.Threading.Tasks.Task<PgContractService.SaveCrmObjectResult> PendingContractAsync(string userName, string password, System.Guid contractId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/NumberedContract", ReplyAction="http://tempuri.org/IContract/NumberedContractResponse")]
        PgContractService.SaveCrmObjectResult NumberedContract(string userName, string password, System.Guid contractId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/NumberedContract", ReplyAction="http://tempuri.org/IContract/NumberedContractResponse")]
        System.Threading.Tasks.Task<PgContractService.SaveCrmObjectResult> NumberedContractAsync(string userName, string password, System.Guid contractId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IContractChannel : PgContractService.IContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ContractClient : System.ServiceModel.ClientBase<PgContractService.IContract>, PgContractService.IContract
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ContractClient() : 
                base(ContractClient.GetDefaultBinding(), ContractClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IContract.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContractClient(EndpointConfiguration endpointConfiguration) : 
                base(ContractClient.GetBindingForEndpoint(endpointConfiguration), ContractClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContractClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ContractClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContractClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ContractClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PgContractService.SaveCrmObjectResult SaveContract(string userName, string password, PgContractService.ContractInfo contractInfo)
        {
            return base.Channel.SaveContract(userName, password, contractInfo);
        }
        
        public System.Threading.Tasks.Task<PgContractService.SaveCrmObjectResult> SaveContractAsync(string userName, string password, PgContractService.ContractInfo contractInfo)
        {
            return base.Channel.SaveContractAsync(userName, password, contractInfo);
        }
        
        public PgContractService.ContractInfoResult SearchContract(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchContract(userName, password, typeKey, query);
        }
        
        public System.Threading.Tasks.Task<PgContractService.ContractInfoResult> SearchContractAsync(string userName, string password, string typeKey, string query)
        {
            return base.Channel.SearchContractAsync(userName, password, typeKey, query);
        }
        
        public PgContractService.ContractInfoResult FindContractById(string userName, string password, System.Guid contractId)
        {
            return base.Channel.FindContractById(userName, password, contractId);
        }
        
        public System.Threading.Tasks.Task<PgContractService.ContractInfoResult> FindContractByIdAsync(string userName, string password, System.Guid contractId)
        {
            return base.Channel.FindContractByIdAsync(userName, password, contractId);
        }
        
        public PgContractService.SaveCrmObjectResult DeleteContractById(string userName, string password, System.Guid contractId, PgContractService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteContractById(userName, password, contractId, deleteOption);
        }
        
        public System.Threading.Tasks.Task<PgContractService.SaveCrmObjectResult> DeleteContractByIdAsync(string userName, string password, System.Guid contractId, PgContractService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteContractByIdAsync(userName, password, contractId, deleteOption);
        }
        
        public PgContractService.SaveCrmObjectResult ApprovedContract(string userName, string password, System.Guid contractId)
        {
            return base.Channel.ApprovedContract(userName, password, contractId);
        }
        
        public System.Threading.Tasks.Task<PgContractService.SaveCrmObjectResult> ApprovedContractAsync(string userName, string password, System.Guid contractId)
        {
            return base.Channel.ApprovedContractAsync(userName, password, contractId);
        }
        
        public PgContractService.SaveCrmObjectResult RejectedContract(string userName, string password, System.Guid contractId)
        {
            return base.Channel.RejectedContract(userName, password, contractId);
        }
        
        public System.Threading.Tasks.Task<PgContractService.SaveCrmObjectResult> RejectedContractAsync(string userName, string password, System.Guid contractId)
        {
            return base.Channel.RejectedContractAsync(userName, password, contractId);
        }
        
        public PgContractService.SaveCrmObjectResult PendingContract(string userName, string password, System.Guid contractId)
        {
            return base.Channel.PendingContract(userName, password, contractId);
        }
        
        public System.Threading.Tasks.Task<PgContractService.SaveCrmObjectResult> PendingContractAsync(string userName, string password, System.Guid contractId)
        {
            return base.Channel.PendingContractAsync(userName, password, contractId);
        }
        
        public PgContractService.SaveCrmObjectResult NumberedContract(string userName, string password, System.Guid contractId)
        {
            return base.Channel.NumberedContract(userName, password, contractId);
        }
        
        public System.Threading.Tasks.Task<PgContractService.SaveCrmObjectResult> NumberedContractAsync(string userName, string password, System.Guid contractId)
        {
            return base.Channel.NumberedContractAsync(userName, password, contractId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IContract))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IContract))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.11.9/Services/API/IContract.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ContractClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IContract);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ContractClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IContract);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IContract,
        }
    }
}
