//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgCrmObjectService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgCrmObjectService.SaveCrmObjectResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgCrmObjectService.CrmObjectCollectionInfoResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgCrmObjectService.CrmObjectInfoResult))]
    public partial class OperationResult : object
    {
        
        private string MessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveCrmObjectResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class SaveCrmObjectResult : PgCrmObjectService.OperationResult
    {
        
        private System.Guid CrmIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CrmId
        {
            get
            {
                return this.CrmIdField;
            }
            set
            {
                this.CrmIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectCollectionInfoResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class CrmObjectCollectionInfoResult : PgCrmObjectService.OperationResult
    {
        
        private PgCrmObjectService.CrmObjectInfo[] CrmObjectInfosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgCrmObjectService.CrmObjectInfo[] CrmObjectInfos
        {
            get
            {
                return this.CrmObjectInfosField;
            }
            set
            {
                this.CrmObjectInfosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectInfoResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class CrmObjectInfoResult : PgCrmObjectService.OperationResult
    {
        
        private PgCrmObjectService.CrmObjectInfo CrmObjectInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgCrmObjectService.CrmObjectInfo CrmObjectInfo
        {
            get
            {
                return this.CrmObjectInfoField;
            }
            set
            {
                this.CrmObjectInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class CrmObjectInfo : PgCrmObjectService.GeneralCrmObjectInfo
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgCrmObjectService.GeneralCrmObjectInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgCrmObjectService.CrmObjectInfo))]
    public partial class BaseCrmObjectInfo : object
    {
        
        private System.DateTime CreatDateField;
        
        private System.Nullable<System.Guid> CrmIdField;
        
        private string CrmObjectTypeCodeField;
        
        private System.Guid CrmObjectTypeIdField;
        
        private int CrmObjectTypeIndexField;
        
        private string CrmObjectTypeNameField;
        
        private PgCrmObjectService.BaseCrmObjectExtendedPropertyInfo[] ExtendedPropertiesField;
        
        private System.DateTime ModifyDateField;
        
        private System.Nullable<System.Guid> ParentCrmObjectIdField;
        
        private System.Nullable<int> ProcessStateIndexField;
        
        private string RefIdField;
        
        private string StageField;
        
        private System.Nullable<System.Guid> StageIdField;
        
        private string[] TagsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatDate
        {
            get
            {
                return this.CreatDateField;
            }
            set
            {
                this.CreatDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CrmId
        {
            get
            {
                return this.CrmIdField;
            }
            set
            {
                this.CrmIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeCode
        {
            get
            {
                return this.CrmObjectTypeCodeField;
            }
            set
            {
                this.CrmObjectTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CrmObjectTypeId
        {
            get
            {
                return this.CrmObjectTypeIdField;
            }
            set
            {
                this.CrmObjectTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrmObjectTypeIndex
        {
            get
            {
                return this.CrmObjectTypeIndexField;
            }
            set
            {
                this.CrmObjectTypeIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmObjectTypeName
        {
            get
            {
                return this.CrmObjectTypeNameField;
            }
            set
            {
                this.CrmObjectTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgCrmObjectService.BaseCrmObjectExtendedPropertyInfo[] ExtendedProperties
        {
            get
            {
                return this.ExtendedPropertiesField;
            }
            set
            {
                this.ExtendedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifyDate
        {
            get
            {
                return this.ModifyDateField;
            }
            set
            {
                this.ModifyDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentCrmObjectId
        {
            get
            {
                return this.ParentCrmObjectIdField;
            }
            set
            {
                this.ParentCrmObjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProcessStateIndex
        {
            get
            {
                return this.ProcessStateIndexField;
            }
            set
            {
                this.ProcessStateIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId
        {
            get
            {
                return this.RefIdField;
            }
            set
            {
                this.RefIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stage
        {
            get
            {
                return this.StageField;
            }
            set
            {
                this.StageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> StageId
        {
            get
            {
                return this.StageIdField;
            }
            set
            {
                this.StageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralCrmObjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PgCrmObjectService.CrmObjectInfo))]
    public partial class GeneralCrmObjectInfo : PgCrmObjectService.BaseCrmObjectInfo
    {
        
        private string DescriptionField;
        
        private System.Nullable<System.Guid> IdentityIdField;
        
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> IdentityId
        {
            get
            {
                return this.IdentityIdField;
            }
            set
            {
                this.IdentityIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCrmObjectExtendedPropertyInfo", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class BaseCrmObjectExtendedPropertyInfo : object
    {
        
        private string NameField;
        
        private string UserKeyField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectSearchResult", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.ServiceLayer.Contract.P" +
        "GContracts.DataContracts")]
    public partial class CrmObjectSearchResult : object
    {
        
        private PgCrmObjectService.CrmObjectInfo[] CrmObjectInfoListField;
        
        private string MessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PgCrmObjectService.CrmObjectInfo[] CrmObjectInfoList
        {
            get
            {
                return this.CrmObjectInfoListField;
            }
            set
            {
                this.CrmObjectInfoListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectDeleteOption", Namespace="http://schemas.datacontract.org/2004/07/Septa.PayamGostar.Domain.Model")]
    public enum CrmObjectDeleteOption : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssignChildrenToParent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteChildren = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nothing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeletePersons = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteWithHistory = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PgCrmObjectService.ICrmObject")]
    public interface ICrmObject
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObject/FindCrmObjectById", ReplyAction="http://tempuri.org/ICrmObject/FindCrmObjectByIdResponse")]
        PgCrmObjectService.CrmObjectInfoResult FindCrmObjectById(string userName, string password, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObject/FindCrmObjectById", ReplyAction="http://tempuri.org/ICrmObject/FindCrmObjectByIdResponse")]
        System.Threading.Tasks.Task<PgCrmObjectService.CrmObjectInfoResult> FindCrmObjectByIdAsync(string userName, string password, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObject/Search", ReplyAction="http://tempuri.org/ICrmObject/SearchResponse")]
        PgCrmObjectService.CrmObjectSearchResult Search(string userName, string password, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObject/Search", ReplyAction="http://tempuri.org/ICrmObject/SearchResponse")]
        System.Threading.Tasks.Task<PgCrmObjectService.CrmObjectSearchResult> SearchAsync(string userName, string password, string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObject/DeleteCrmObjectById", ReplyAction="http://tempuri.org/ICrmObject/DeleteCrmObjectByIdResponse")]
        PgCrmObjectService.SaveCrmObjectResult DeleteCrmObjectById(string userName, string password, System.Guid crmId, PgCrmObjectService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObject/DeleteCrmObjectById", ReplyAction="http://tempuri.org/ICrmObject/DeleteCrmObjectByIdResponse")]
        System.Threading.Tasks.Task<PgCrmObjectService.SaveCrmObjectResult> DeleteCrmObjectByIdAsync(string userName, string password, System.Guid crmId, PgCrmObjectService.CrmObjectDeleteOption deleteOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObject/GetCrmObjectHistory", ReplyAction="http://tempuri.org/ICrmObject/GetCrmObjectHistoryResponse")]
        PgCrmObjectService.CrmObjectCollectionInfoResult GetCrmObjectHistory(string userName, string password, System.Guid crmObjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmObject/GetCrmObjectHistory", ReplyAction="http://tempuri.org/ICrmObject/GetCrmObjectHistoryResponse")]
        System.Threading.Tasks.Task<PgCrmObjectService.CrmObjectCollectionInfoResult> GetCrmObjectHistoryAsync(string userName, string password, System.Guid crmObjectId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ICrmObjectChannel : PgCrmObjectService.ICrmObject, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CrmObjectClient : System.ServiceModel.ClientBase<PgCrmObjectService.ICrmObject>, PgCrmObjectService.ICrmObject
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CrmObjectClient() : 
                base(CrmObjectClient.GetDefaultBinding(), CrmObjectClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICrmObject.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrmObjectClient(EndpointConfiguration endpointConfiguration) : 
                base(CrmObjectClient.GetBindingForEndpoint(endpointConfiguration), CrmObjectClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrmObjectClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CrmObjectClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrmObjectClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CrmObjectClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CrmObjectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PgCrmObjectService.CrmObjectInfoResult FindCrmObjectById(string userName, string password, System.Guid id)
        {
            return base.Channel.FindCrmObjectById(userName, password, id);
        }
        
        public System.Threading.Tasks.Task<PgCrmObjectService.CrmObjectInfoResult> FindCrmObjectByIdAsync(string userName, string password, System.Guid id)
        {
            return base.Channel.FindCrmObjectByIdAsync(userName, password, id);
        }
        
        public PgCrmObjectService.CrmObjectSearchResult Search(string userName, string password, string query)
        {
            return base.Channel.Search(userName, password, query);
        }
        
        public System.Threading.Tasks.Task<PgCrmObjectService.CrmObjectSearchResult> SearchAsync(string userName, string password, string query)
        {
            return base.Channel.SearchAsync(userName, password, query);
        }
        
        public PgCrmObjectService.SaveCrmObjectResult DeleteCrmObjectById(string userName, string password, System.Guid crmId, PgCrmObjectService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteCrmObjectById(userName, password, crmId, deleteOption);
        }
        
        public System.Threading.Tasks.Task<PgCrmObjectService.SaveCrmObjectResult> DeleteCrmObjectByIdAsync(string userName, string password, System.Guid crmId, PgCrmObjectService.CrmObjectDeleteOption deleteOption)
        {
            return base.Channel.DeleteCrmObjectByIdAsync(userName, password, crmId, deleteOption);
        }
        
        public PgCrmObjectService.CrmObjectCollectionInfoResult GetCrmObjectHistory(string userName, string password, System.Guid crmObjectId)
        {
            return base.Channel.GetCrmObjectHistory(userName, password, crmObjectId);
        }
        
        public System.Threading.Tasks.Task<PgCrmObjectService.CrmObjectCollectionInfoResult> GetCrmObjectHistoryAsync(string userName, string password, System.Guid crmObjectId)
        {
            return base.Channel.GetCrmObjectHistoryAsync(userName, password, crmObjectId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICrmObject))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICrmObject))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.11.9/Services/API/ICrmObject.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CrmObjectClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICrmObject);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CrmObjectClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICrmObject);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICrmObject,
        }
    }
}
